// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Advice
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service for the `advice` resource.
  ///
  /// @Snippet(path: "adviceQuickstart")
  public protocol Advice {
    /// Advise how, where and when to create the requested amount of instances
    /// with specified accelerators, within the specified time and location limits.
    /// The method recommends creating future reservations for the requested
    /// resources.
    ///
    /// @Snippet(path: "advice_calendarMode")
    func calendarMode(request: Clients.AdviceClient.CalendarModeRequest) async throws
      -> GoogleCloudComputeV1.CalendarModeAdviceResponse

    /// Advise how, where and when to create the requested amount of instances
    /// with specified accelerators, within the specified time and location limits.
    /// The method recommends creating future reservations for the requested
    /// resources.
    func calendarMode(
      project: Swift.String,
      region: Swift.String,
      body: CalendarModeAdviceRequest?,
    ) async throws -> GoogleCloudComputeV1.CalendarModeAdviceResponse

    /// Advise how, where and when to create the requested amount of instances
    /// with specified accelerators, within the specified time and location limits.
    /// The method recommends creating future reservations for the requested
    /// resources.
    ///
    /// @Snippet(path: "advice_calendarMode")
    func calendarMode(
      request: Clients.AdviceClient.CalendarModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CalendarModeAdviceResponse
  }

  extension Clients {
    /// The recommended implementation for ``Advice``.
    public class AdviceClient: Advice {
      let inner: any AdviceStub

      /// Creates a new `AdviceClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any AdviceStub = try AdviceTransport(options)
        inner = AdviceRetry(inner, options: options)
        if let logger = options.logger {
          inner = AdviceLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `Advice.calendarMode`
      public func calendarMode(
        request: Clients.AdviceClient.CalendarModeRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.CalendarModeAdviceResponse {
        try await self.inner.calendarMode(request: request, options: options)
      }
    }
  }

  // Default implementations
  extension Advice {
    public func calendarMode(request: Clients.AdviceClient.CalendarModeRequest) async throws
      -> GoogleCloudComputeV1.CalendarModeAdviceResponse
    {
      try await self.calendarMode(request: request, options: .init())
    }

    public func calendarMode(
      request: Clients.AdviceClient.CalendarModeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CalendarModeAdviceResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func calendarMode(
      project: Swift.String,
      region: Swift.String,
      body: CalendarModeAdviceRequest?,
    ) async throws -> GoogleCloudComputeV1.CalendarModeAdviceResponse {
      let request = Clients.AdviceClient.CalendarModeRequest().with {
        $0.project = project
        $0.region = region
        $0.body = body
      }
      return try await self.calendarMode(request: request)
    }
  }
#endif
