// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if BackendServices
  import Foundation
  import GoogleCloudWkt
  import GoogleCloudGax

  extension Clients {
    protocol BackendServicesStub: Sendable {
      func addSignedUrlKey(
        request: BackendServicesClient.AddSignedUrlKeyRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func aggregatedList(
        request: BackendServicesClient.AggregatedListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.BackendServiceAggregatedList

      func delete(
        request: BackendServicesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func deleteSignedUrlKey(
        request: BackendServicesClient.DeleteSignedUrlKeyRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func `get`(
        request: BackendServicesClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.BackendService

      func getEffectiveSecurityPolicies(
        request: BackendServicesClient.GetEffectiveSecurityPoliciesRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws

      func getHealth(
        request: BackendServicesClient.GetHealthRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.BackendServiceGroupHealth

      func getIamPolicy(
        request: BackendServicesClient.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy

      func insert(
        request: BackendServicesClient.InsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func list(
        request: BackendServicesClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.BackendServiceList

      func listUsable(
        request: BackendServicesClient.ListUsableRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.BackendServiceListUsable

      func patch(
        request: BackendServicesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func setEdgeSecurityPolicy(
        request: BackendServicesClient.SetEdgeSecurityPolicyRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func setIamPolicy(
        request: BackendServicesClient.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy

      func setSecurityPolicy(
        request: BackendServicesClient.SetSecurityPolicyRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func testIamPermissions(
        request: BackendServicesClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse

      func update(
        request: BackendServicesClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func getOperation(
        request: GlobalOperationsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation
    }
  }
#endif
