// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if BackendServices || RegionBackendServices
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Message containing what to include in the cache key for a request for Cloud
  /// CDN.
  public struct CacheKeyPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// If true, requests to different hosts will be cached separately.
    public var includeHost: Swift.Bool? = nil

    /// Allows HTTP request headers (by name) to be used in the cache key.
    public var includeHttpHeaders: [Swift.String] = []

    /// Allows HTTP cookies (by name) to be used in the cache key.
    /// The name=value pair will be used in the cache key Cloud CDN generates.
    public var includeNamedCookies: [Swift.String] = []

    /// If true, http and https requests will be cached separately.
    public var includeProtocol: Swift.Bool? = nil

    /// If true, include query string parameters in the cache key according to
    /// query_string_whitelist and query_string_blacklist. If neither is set, the
    /// entire query string will be included. If false, the query string will be
    /// excluded from the cache key entirely.
    public var includeQueryString: Swift.Bool? = nil

    /// Names of query string parameters to exclude in cache keys. All other
    /// parameters will be included. Either specify query_string_whitelist or
    /// query_string_blacklist, not both. '&' and '=' will be percent encoded and
    /// not treated as delimiters.
    public var queryStringBlacklist: [Swift.String] = []

    /// Names of query string parameters to include in cache keys. All other
    /// parameters will be excluded. Either specify query_string_whitelist or
    /// query_string_blacklist, not both. '&' and '=' will be percent encoded and
    /// not treated as delimiters.
    public var queryStringWhitelist: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CacheKeyPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CacheKeyPolicy().with { $0.includeHost = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let includeHost = CodingKeys(stringValue: "includeHost")
      static let includeHttpHeaders = CodingKeys(stringValue: "includeHttpHeaders")
      static let includeNamedCookies = CodingKeys(stringValue: "includeNamedCookies")
      static let includeProtocol = CodingKeys(stringValue: "includeProtocol")
      static let includeQueryString = CodingKeys(stringValue: "includeQueryString")
      static let queryStringBlacklist = CodingKeys(stringValue: "queryStringBlacklist")
      static let queryStringWhitelist = CodingKeys(stringValue: "queryStringWhitelist")

      static let _knownKeys: Set<Swift.String> = [
        "includeHost",
        "includeHttpHeaders",
        "includeNamedCookies",
        "includeProtocol",
        "includeQueryString",
        "queryStringBlacklist",
        "queryStringWhitelist",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.includeHost = try container.decodeIfPresent(Swift.Bool.self, forKey: .includeHost)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .includeHttpHeaders)
      {
        self.includeHttpHeaders = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .includeNamedCookies)
      {
        self.includeNamedCookies = value
      }
      self.includeProtocol = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .includeProtocol)
      self.includeQueryString = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .includeQueryString)
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .queryStringBlacklist)
      {
        self.queryStringBlacklist = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .queryStringWhitelist)
      {
        self.queryStringWhitelist = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.includeHost, forKey: .includeHost)
      try container.encode(self.includeHttpHeaders, forKey: .includeHttpHeaders)
      try container.encode(self.includeNamedCookies, forKey: .includeNamedCookies)
      try container.encodeIfPresent(self.includeProtocol, forKey: .includeProtocol)
      try container.encodeIfPresent(self.includeQueryString, forKey: .includeQueryString)
      try container.encode(self.queryStringBlacklist, forKey: .queryStringBlacklist)
      try container.encode(self.queryStringWhitelist, forKey: .queryStringWhitelist)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.CacheKeyPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
