// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Advice
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Machine specification.
  public struct CapacityAdviceRequestInstanceFlexibilityPolicyInstanceSelection: Codable, Equatable,
    GoogleWKT._AnyPackable,
    Sendable
  {
    /// Local SSDs.
    public var disks:
      [CapacityAdviceRequestInstanceFlexibilityPolicyInstanceSelectionAttachedDisk] = []

    /// Accelerators configuration.
    public var guestAccelerators: [AcceleratorConfig] = []

    /// Full machine-type names, e.g. "n1-standard-16".
    public var machineTypes: [Swift.String] = []

    /// Optional. Rank when prioritizing the shape flexibilities.
    /// The instance selections are considered in the ascending order of the
    /// rank. If not set, defaults to 0.
    public var rank: Swift.Int64? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CapacityAdviceRequestInstanceFlexibilityPolicyInstanceSelection`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CapacityAdviceRequestInstanceFlexibilityPolicyInstanceSelection().with { $0.disks = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let disks = CodingKeys(stringValue: "disks")
      static let guestAccelerators = CodingKeys(stringValue: "guestAccelerators")
      static let machineTypes = CodingKeys(stringValue: "machineTypes")
      static let rank = CodingKeys(stringValue: "rank")

      static let _knownKeys: Set<Swift.String> = [
        "disks",
        "guestAccelerators",
        "machineTypes",
        "rank",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [CapacityAdviceRequestInstanceFlexibilityPolicyInstanceSelectionAttachedDisk].self,
        forKey: .disks)
      {
        self.disks = value
      }
      if let value = try container.decodeIfPresent(
        [AcceleratorConfig].self, forKey: .guestAccelerators)
      {
        self.guestAccelerators = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .machineTypes) {
        self.machineTypes = value
      }
      self.rank = try container.decodeIfPresent(Swift.Int64.self, forKey: .rank)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.disks, forKey: .disks)
      try container.encode(self.guestAccelerators, forKey: .guestAccelerators)
      try container.encode(self.machineTypes, forKey: .machineTypes)
      try container.encodeIfPresent(self.rank, forKey: .rank)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.compute.v1.CapacityAdviceRequestInstanceFlexibilityPolicyInstanceSelection"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
