// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ExternalVpnGateways
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service for the `externalVpnGateways` resource.
  ///
  /// @Snippet(path: "externalVpnGatewaysQuickstart")
  public protocol ExternalVpnGateways {
    /// Deletes the specified externalVpnGateway.
    ///
    /// @Snippet(path: "externalVpnGateways_delete")
    func delete(request: Clients.ExternalVpnGatewaysClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Deletes the specified externalVpnGateway.
    func delete(
      project: Swift.String,
      externalVpnGateway: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns the specified externalVpnGateway. Get a list of available
    /// externalVpnGateways by making a list() request.
    ///
    /// @Snippet(path: "externalVpnGateways_get")
    func `get`(request: Clients.ExternalVpnGatewaysClient.GetRequest) async throws
      -> GoogleCloudComputeV1.ExternalVpnGateway

    /// Returns the specified externalVpnGateway. Get a list of available
    /// externalVpnGateways by making a list() request.
    func `get`(
      project: Swift.String,
      externalVpnGateway: Swift.String,
    ) async throws -> GoogleCloudComputeV1.ExternalVpnGateway

    /// Creates a ExternalVpnGateway in the specified project using
    /// the data included in the request.
    ///
    /// @Snippet(path: "externalVpnGateways_insert")
    func insert(request: Clients.ExternalVpnGatewaysClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Creates a ExternalVpnGateway in the specified project using
    /// the data included in the request.
    func insert(
      project: Swift.String,
      body: ExternalVpnGateway?,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Retrieves the list of ExternalVpnGateway available to the specified
    /// project.
    ///
    /// @Snippet(path: "externalVpnGateways_list")
    func list(request: Clients.ExternalVpnGatewaysClient.ListRequest) async throws
      -> GoogleCloudComputeV1.ExternalVpnGatewayList

    /// Retrieves the list of ExternalVpnGateway available to the specified
    /// project.
    func list(
      byItem: Clients.ExternalVpnGatewaysClient.ListRequest
    ) throws -> any AsyncSequence<ExternalVpnGateway, Swift.Error>

    /// Retrieves the list of ExternalVpnGateway available to the specified
    /// project.
    func list(
      project: Swift.String,
    ) throws -> any AsyncSequence<ExternalVpnGateway, Swift.Error>

    /// Sets the labels on an ExternalVpnGateway. To learn more about labels,
    /// read the Labeling
    /// Resources documentation.
    ///
    /// @Snippet(path: "externalVpnGateways_setLabels")
    func setLabels(request: Clients.ExternalVpnGatewaysClient.SetLabelsRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Sets the labels on an ExternalVpnGateway. To learn more about labels,
    /// read the Labeling
    /// Resources documentation.
    func setLabels(
      project: Swift.String,
      resource: Swift.String,
      body: GlobalSetLabelsRequest?,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns permissions that a caller has on the specified resource.
    ///
    /// @Snippet(path: "externalVpnGateways_testIamPermissions")
    func testIamPermissions(request: Clients.ExternalVpnGatewaysClient.TestIamPermissionsRequest)
      async throws -> GoogleCloudComputeV1.TestPermissionsResponse

    /// Returns permissions that a caller has on the specified resource.
    func testIamPermissions(
      project: Swift.String,
      resource: Swift.String,
      body: TestPermissionsRequest?,
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse

    /// Deletes the specified externalVpnGateway.
    ///
    /// @Snippet(path: "externalVpnGateways_delete")
    func delete(
      request: Clients.ExternalVpnGatewaysClient.DeleteRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns the specified externalVpnGateway. Get a list of available
    /// externalVpnGateways by making a list() request.
    ///
    /// @Snippet(path: "externalVpnGateways_get")
    func `get`(
      request: Clients.ExternalVpnGatewaysClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.ExternalVpnGateway

    /// Creates a ExternalVpnGateway in the specified project using
    /// the data included in the request.
    ///
    /// @Snippet(path: "externalVpnGateways_insert")
    func insert(
      request: Clients.ExternalVpnGatewaysClient.InsertRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Retrieves the list of ExternalVpnGateway available to the specified
    /// project.
    ///
    /// @Snippet(path: "externalVpnGateways_list")
    func list(
      request: Clients.ExternalVpnGatewaysClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.ExternalVpnGatewayList

    /// Retrieves the list of ExternalVpnGateway available to the specified
    /// project.
    func list(
      byItem: Clients.ExternalVpnGatewaysClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ExternalVpnGateway, Swift.Error>

    /// Sets the labels on an ExternalVpnGateway. To learn more about labels,
    /// read the Labeling
    /// Resources documentation.
    ///
    /// @Snippet(path: "externalVpnGateways_setLabels")
    func setLabels(
      request: Clients.ExternalVpnGatewaysClient.SetLabelsRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns permissions that a caller has on the specified resource.
    ///
    /// @Snippet(path: "externalVpnGateways_testIamPermissions")
    func testIamPermissions(
      request: Clients.ExternalVpnGatewaysClient.TestIamPermissionsRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse
  }

  extension Clients {
    /// The recommended implementation for ``ExternalVpnGateways``.
    public class ExternalVpnGatewaysClient: ExternalVpnGateways {
      let inner: any ExternalVpnGatewaysStub

      /// Creates a new `ExternalVpnGatewaysClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any ExternalVpnGatewaysStub = try ExternalVpnGatewaysTransport(options)
        inner = ExternalVpnGatewaysRetry(inner, options: options)
        if let logger = options.logger {
          inner = ExternalVpnGatewaysLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `ExternalVpnGateways.delete`
      public func delete(
        request: Clients.ExternalVpnGatewaysClient.DeleteRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.delete(request: request, options: options)
      }

      /// See `ExternalVpnGateways.`get``
      public func `get`(
        request: Clients.ExternalVpnGatewaysClient.GetRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.ExternalVpnGateway {
        try await self.inner.`get`(request: request, options: options)
      }

      /// See `ExternalVpnGateways.insert`
      public func insert(
        request: Clients.ExternalVpnGatewaysClient.InsertRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.insert(request: request, options: options)
      }

      /// See `ExternalVpnGateways.list`
      public func list(
        request: Clients.ExternalVpnGatewaysClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.ExternalVpnGatewayList {
        try await self.inner.list(request: request, options: options)
      }

      /// Retrieves the list of ExternalVpnGateway available to the specified
      /// project.
      public func list(
        byItem: Clients.ExternalVpnGatewaysClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<ExternalVpnGateway, Swift.Error> {
        let listRpc = {
          (token: String) async throws -> GoogleCloudComputeV1.ExternalVpnGatewayList in
          var request = byItem
          request.pageToken = token
          return try await self.list(request: request, options: options)
        }
        return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
      }

      /// See `ExternalVpnGateways.setLabels`
      public func setLabels(
        request: Clients.ExternalVpnGatewaysClient.SetLabelsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.setLabels(request: request, options: options)
      }

      /// See `ExternalVpnGateways.testIamPermissions`
      public func testIamPermissions(
        request: Clients.ExternalVpnGatewaysClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self.inner.testIamPermissions(request: request, options: options)
      }
    }
  }

  // Default implementations
  extension ExternalVpnGateways {
    public func delete(request: Clients.ExternalVpnGatewaysClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: Clients.ExternalVpnGatewaysClient.DeleteRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func delete(
      project: Swift.String,
      externalVpnGateway: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.ExternalVpnGatewaysClient.DeleteRequest().with {
        $0.project = project
        $0.externalVpnGateway = externalVpnGateway
      }
      return try await self.delete(request: request)
    }

    public func `get`(request: Clients.ExternalVpnGatewaysClient.GetRequest) async throws
      -> GoogleCloudComputeV1.ExternalVpnGateway
    {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: Clients.ExternalVpnGatewaysClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.ExternalVpnGateway {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func `get`(
      project: Swift.String,
      externalVpnGateway: Swift.String,
    ) async throws -> GoogleCloudComputeV1.ExternalVpnGateway {
      let request = Clients.ExternalVpnGatewaysClient.GetRequest().with {
        $0.project = project
        $0.externalVpnGateway = externalVpnGateway
      }
      return try await self.`get`(request: request)
    }

    public func insert(request: Clients.ExternalVpnGatewaysClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.insert(request: request, options: .init())
    }

    public func insert(
      request: Clients.ExternalVpnGatewaysClient.InsertRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func insert(
      project: Swift.String,
      body: ExternalVpnGateway?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.ExternalVpnGatewaysClient.InsertRequest().with {
        $0.project = project
        $0.body = body
      }
      return try await self.insert(request: request)
    }

    public func list(request: Clients.ExternalVpnGatewaysClient.ListRequest) async throws
      -> GoogleCloudComputeV1.ExternalVpnGatewayList
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: Clients.ExternalVpnGatewaysClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.ExternalVpnGatewayList {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(
      byItem: Clients.ExternalVpnGatewaysClient.ListRequest
    ) throws -> any AsyncSequence<ExternalVpnGateway, Swift.Error> {
      try self.list(byItem: byItem, options: .init())
    }

    public func list(
      byItem: Clients.ExternalVpnGatewaysClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ExternalVpnGateway, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudComputeV1.ExternalVpnGatewayList in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func list(
      project: Swift.String,
    ) throws -> any AsyncSequence<ExternalVpnGateway, Swift.Error> {
      let request = Clients.ExternalVpnGatewaysClient.ListRequest().with {
        $0.project = project
      }
      return try self.list(byItem: request)
    }

    public func setLabels(request: Clients.ExternalVpnGatewaysClient.SetLabelsRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.setLabels(request: request, options: .init())
    }

    public func setLabels(
      request: Clients.ExternalVpnGatewaysClient.SetLabelsRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func setLabels(
      project: Swift.String,
      resource: Swift.String,
      body: GlobalSetLabelsRequest?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.ExternalVpnGatewaysClient.SetLabelsRequest().with {
        $0.project = project
        $0.resource = resource
        $0.body = body
      }
      return try await self.setLabels(request: request)
    }

    public func testIamPermissions(
      request: Clients.ExternalVpnGatewaysClient.TestIamPermissionsRequest
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      try await self.testIamPermissions(request: request, options: .init())
    }

    public func testIamPermissions(
      request: Clients.ExternalVpnGatewaysClient.TestIamPermissionsRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func testIamPermissions(
      project: Swift.String,
      resource: Swift.String,
      body: TestPermissionsRequest?,
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      let request = Clients.ExternalVpnGatewaysClient.TestIamPermissionsRequest().with {
        $0.project = project
        $0.resource = resource
        $0.body = body
      }
      return try await self.testIamPermissions(request: request)
    }
  }
#endif
