// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FirewallPolicies
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  extension Clients {
    final class FirewallPoliciesRetry: FirewallPoliciesStub {
      let inner: any FirewallPoliciesStub
      let options: GoogleCloudGax.ClientOptions

      public init(_ inner: any FirewallPoliciesStub, options: GoogleCloudGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func addAssociation(
        request: FirewallPoliciesClient.AddAssociationRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.AddAssociationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.addAssociation(request: r, options: o)
          })
      }

      public func addRule(
        request: FirewallPoliciesClient.AddRuleRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.AddRuleRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.addRule(request: r, options: o)
          })
      }

      public func cloneRules(
        request: FirewallPoliciesClient.CloneRulesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.CloneRulesRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.cloneRules(request: r, options: o)
          })
      }

      public func delete(
        request: FirewallPoliciesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.DeleteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func `get`(
        request: FirewallPoliciesClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.FirewallPolicy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: FirewallPoliciesClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.FirewallPolicy
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func getAssociation(
        request: FirewallPoliciesClient.GetAssociationRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.FirewallPolicyAssociation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: FirewallPoliciesClient.GetAssociationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.FirewallPolicyAssociation
            in
            return try await self.inner.getAssociation(request: r, options: o)
          })
      }

      public func getIamPolicy(
        request: FirewallPoliciesClient.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: FirewallPoliciesClient.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Policy
            in
            return try await self.inner.getIamPolicy(request: r, options: o)
          })
      }

      public func getRule(
        request: FirewallPoliciesClient.GetRuleRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.FirewallPolicyRule {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: FirewallPoliciesClient.GetRuleRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.FirewallPolicyRule
            in
            return try await self.inner.getRule(request: r, options: o)
          })
      }

      public func insert(
        request: FirewallPoliciesClient.InsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.InsertRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: FirewallPoliciesClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.FirewallPolicyList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: FirewallPoliciesClient.ListRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.FirewallPolicyList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func listAssociations(
        request: FirewallPoliciesClient.ListAssociationsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.FirewallPoliciesListAssociationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: FirewallPoliciesClient.ListAssociationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.FirewallPoliciesListAssociationsResponse
            in
            return try await self.inner.listAssociations(request: r, options: o)
          })
      }

      public func move(
        request: FirewallPoliciesClient.MoveRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.MoveRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.move(request: r, options: o)
          })
      }

      public func patch(
        request: FirewallPoliciesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.PatchRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.patch(request: r, options: o)
          })
      }

      public func patchRule(
        request: FirewallPoliciesClient.PatchRuleRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.PatchRuleRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.patchRule(request: r, options: o)
          })
      }

      public func removeAssociation(
        request: FirewallPoliciesClient.RemoveAssociationRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.RemoveAssociationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.removeAssociation(request: r, options: o)
          })
      }

      public func removeRule(
        request: FirewallPoliciesClient.RemoveRuleRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.RemoveRuleRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.removeRule(request: r, options: o)
          })
      }

      public func setIamPolicy(
        request: FirewallPoliciesClient.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Policy
            in
            return try await self.inner.setIamPolicy(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: FirewallPoliciesClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: FirewallPoliciesClient.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.TestPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }
    }
  }
#endif
