// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Advice
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Specifies a flexible time range with flexible start time and duration.
  ///
  /// It is possible to specify a contradictory time range that cannot be matched
  /// by any Interval. This causes a validation error.
  public struct FlexibleTimeRange: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var maxDuration: GoogleWKT.WKTDuration? = nil

    public var minDuration: GoogleWKT.WKTDuration? = nil

    public var startTimeNotEarlierThan: GoogleWKT.WKTTimestamp? = nil

    public var startTimeNotLaterThan: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FlexibleTimeRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FlexibleTimeRange().with { $0.maxDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let maxDuration = CodingKeys(stringValue: "maxDuration")
      static let minDuration = CodingKeys(stringValue: "minDuration")
      static let startTimeNotEarlierThan = CodingKeys(stringValue: "startTimeNotEarlierThan")
      static let startTimeNotLaterThan = CodingKeys(stringValue: "startTimeNotLaterThan")

      static let _knownKeys: Set<Swift.String> = [
        "maxDuration",
        "minDuration",
        "startTimeNotEarlierThan",
        "startTimeNotLaterThan",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.maxDuration = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .maxDuration)
      self.minDuration = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .minDuration)
      self.startTimeNotEarlierThan = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .startTimeNotEarlierThan)
      self.startTimeNotLaterThan = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .startTimeNotLaterThan)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.maxDuration, forKey: .maxDuration)
      try container.encodeIfPresent(self.minDuration, forKey: .minDuration)
      try container.encodeIfPresent(self.startTimeNotEarlierThan, forKey: .startTimeNotEarlierThan)
      try container.encodeIfPresent(self.startTimeNotLaterThan, forKey: .startTimeNotLaterThan)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.FlexibleTimeRange"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
