// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if FutureReservations
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// The state that the future reservation will be reverted to should the
  /// amendment be declined.
  public struct FutureReservationStatusLastKnownGoodState: Codable, Equatable, GoogleWKT
      ._AnyPackable,
    Sendable
  {
    /// Output only. [Output Only] The description of the FutureReservation before an
    /// amendment was requested.
    public var description: Swift.String? = nil

    /// Output only. [Output Only] Represents the matching usage for the future
    /// reservation before an amendment was requested.
    public var existingMatchingUsageInfo: FutureReservationStatusExistingMatchingUsageInfo? = nil

    public var futureReservationSpecs:
      FutureReservationStatusLastKnownGoodStateFutureReservationSpecs? = nil

    /// Output only. [Output Only] The lock time of the FutureReservation before an
    /// amendment was requested.
    public var lockTime: Swift.String? = nil

    /// Output only. [Output Only] The name prefix of the Future Reservation before an
    /// amendment was requested.
    public var namePrefix: Swift.String? = nil

    /// Output only. [Output Only] The status of the last known good state for the Future
    /// Reservation.
    public var procurementStatus: FutureReservationStatusLastKnownGoodState.ProcurementStatus? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FutureReservationStatusLastKnownGoodState`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FutureReservationStatusLastKnownGoodState().with { $0.description = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let description = CodingKeys(stringValue: "description")
      static let existingMatchingUsageInfo = CodingKeys(stringValue: "existingMatchingUsageInfo")
      static let futureReservationSpecs = CodingKeys(stringValue: "futureReservationSpecs")
      static let lockTime = CodingKeys(stringValue: "lockTime")
      static let namePrefix = CodingKeys(stringValue: "namePrefix")
      static let procurementStatus = CodingKeys(stringValue: "procurementStatus")

      static let _knownKeys: Set<Swift.String> = [
        "description",
        "existingMatchingUsageInfo",
        "futureReservationSpecs",
        "lockTime",
        "namePrefix",
        "procurementStatus",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
      self.existingMatchingUsageInfo = try container.decodeIfPresent(
        FutureReservationStatusExistingMatchingUsageInfo.self, forKey: .existingMatchingUsageInfo)
      self.futureReservationSpecs = try container.decodeIfPresent(
        FutureReservationStatusLastKnownGoodStateFutureReservationSpecs.self,
        forKey: .futureReservationSpecs)
      self.lockTime = try container.decodeIfPresent(Swift.String.self, forKey: .lockTime)
      self.namePrefix = try container.decodeIfPresent(Swift.String.self, forKey: .namePrefix)
      self.procurementStatus = try container.decodeIfPresent(
        FutureReservationStatusLastKnownGoodState.ProcurementStatus.self, forKey: .procurementStatus
      )
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.description, forKey: .description)
      try container.encodeIfPresent(
        self.existingMatchingUsageInfo, forKey: .existingMatchingUsageInfo)
      try container.encodeIfPresent(self.futureReservationSpecs, forKey: .futureReservationSpecs)
      try container.encodeIfPresent(self.lockTime, forKey: .lockTime)
      try container.encodeIfPresent(self.namePrefix, forKey: .namePrefix)
      try container.encodeIfPresent(self.procurementStatus, forKey: .procurementStatus)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [procurementStatus][google.cloud.compute.v1.FutureReservationStatusLastKnownGoodState.procurementStatus] field.
    ///
    /// [google.cloud.compute.v1.FutureReservationStatusLastKnownGoodState.procurementStatus]: <doc:FutureReservationStatusLastKnownGoodState/ProcurementStatus>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ProcurementStatus: Codable, Equatable, Hashable, Sendable {
      /// Future reservation is approved by GCP.
      case approved
      /// Future reservation is cancelled by the customer.
      case cancelled
      /// Future reservation is committed by the customer.
      case committed
      /// Future reservation is rejected by GCP.
      case declined
      /// Related status for PlanningStatus.Draft. Transitions to
      /// PENDING_APPROVAL upon user submitting FR.
      case drafting
      /// Future reservation failed. No additional reservations were provided.
      case failed
      /// Future reservation is partially fulfilled. Additional reservations were
      /// provided but did not reach total_count reserved instance slots.
      case failedPartiallyFulfilled
      /// Future reservation is fulfilled completely.
      case fulfilled
      /// An Amendment to the Future Reservation has been requested. If the
      /// Amendment is declined, the Future Reservation will be restored to the
      /// last known good state.
      case pendingAmendmentApproval
      /// Future reservation is pending approval by GCP.
      case pendingApproval
      case unspecified
      /// Future reservation is being procured by GCP. Beyond this point, Future
      /// reservation is locked and no further modifications are allowed.
      case procuring
      /// Future reservation capacity is being provisioned. This state will be
      /// entered after start_time, while reservations are being created to
      /// provide total_count reserved instance slots. This state will not
      /// persist past start_time + 24h.
      case provisioning
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .approved: return "APPROVED"
        case .cancelled: return "CANCELLED"
        case .committed: return "COMMITTED"
        case .declined: return "DECLINED"
        case .drafting: return "DRAFTING"
        case .failed: return "FAILED"
        case .failedPartiallyFulfilled: return "FAILED_PARTIALLY_FULFILLED"
        case .fulfilled: return "FULFILLED"
        case .pendingAmendmentApproval: return "PENDING_AMENDMENT_APPROVAL"
        case .pendingApproval: return "PENDING_APPROVAL"
        case .unspecified: return "PROCUREMENT_STATUS_UNSPECIFIED"
        case .procuring: return "PROCURING"
        case .provisioning: return "PROVISIONING"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ProcurementStatus/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "APPROVED": self = .approved
        case "CANCELLED": self = .cancelled
        case "COMMITTED": self = .committed
        case "DECLINED": self = .declined
        case "DRAFTING": self = .drafting
        case "FAILED": self = .failed
        case "FAILED_PARTIALLY_FULFILLED": self = .failedPartiallyFulfilled
        case "FULFILLED": self = .fulfilled
        case "PENDING_AMENDMENT_APPROVAL": self = .pendingAmendmentApproval
        case "PENDING_APPROVAL": self = .pendingApproval
        case "PROCUREMENT_STATUS_UNSPECIFIED": self = .unspecified
        case "PROCURING": self = .procuring
        case "PROVISIONING": self = .provisioning
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .approved: return try container.encode("APPROVED")
        case .cancelled: return try container.encode("CANCELLED")
        case .committed: return try container.encode("COMMITTED")
        case .declined: return try container.encode("DECLINED")
        case .drafting: return try container.encode("DRAFTING")
        case .failed: return try container.encode("FAILED")
        case .failedPartiallyFulfilled: return try container.encode("FAILED_PARTIALLY_FULFILLED")
        case .fulfilled: return try container.encode("FULFILLED")
        case .pendingAmendmentApproval: return try container.encode("PENDING_AMENDMENT_APPROVAL")
        case .pendingApproval: return try container.encode("PENDING_APPROVAL")
        case .unspecified: return try container.encode("PROCUREMENT_STATUS_UNSPECIFIED")
        case .procuring: return try container.encode("PROCURING")
        case .provisioning: return try container.encode("PROVISIONING")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.FutureReservationStatusLastKnownGoodState"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
