// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GlobalVmExtensionPolicies
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Policy for a single extension.
  public struct GlobalVmExtensionPolicyExtensionPolicy: Codable, Equatable, GoogleCloudWKT
      ._AnyPackable,
    Sendable
  {
    /// Optional. The version pinning for the extension.
    /// If empty, the extension will be installed with the latest version
    /// released by the extension producer.
    public var pinnedVersion: Swift.String? = nil

    /// Optional. String configuration. Any string payload that the extension
    /// understands.
    public var stringConfig: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `GlobalVmExtensionPolicyExtensionPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GlobalVmExtensionPolicyExtensionPolicy().with { $0.pinnedVersion = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let pinnedVersion = CodingKeys(stringValue: "pinnedVersion")
      static let stringConfig = CodingKeys(stringValue: "stringConfig")

      static let _knownKeys: Set<Swift.String> = [
        "pinnedVersion",
        "stringConfig",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.pinnedVersion = try container.decodeIfPresent(Swift.String.self, forKey: .pinnedVersion)
      self.stringConfig = try container.decodeIfPresent(Swift.String.self, forKey: .stringConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.pinnedVersion, forKey: .pinnedVersion)
      try container.encodeIfPresent(self.stringConfig, forKey: .stringConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.GlobalVmExtensionPolicyExtensionPolicy"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
