// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GlobalVmExtensionPolicies
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Message describing GlobalVmExtensionPolicy object.
  public struct GlobalVmExtensionPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. [Output Only] Creation timestamp inRFC3339
    /// text format.
    public var creationTimestamp: Swift.String? = nil

    /// An optional description of this resource. Provide this property when you
    /// create the resource.
    public var description: Swift.String? = nil

    /// Required. Map from extension (eg: "cloudops") to its policy configuration.
    /// The key is the name of the extension.
    public var extensionPolicies: [Swift.String: GlobalVmExtensionPolicyExtensionPolicy] = [:]

    /// Output only. [Output Only] The unique identifier for the resource. This identifier is
    /// defined by the server.
    public var id: Swift.UInt64? = nil

    /// Optional. Selector to target VMs for a policy.
    /// There is a logical "AND" between instance_selectors.
    public var instanceSelectors: [GlobalVmExtensionPolicyInstanceSelector] = []

    /// Output only. [Output Only] Type of the resource. Alwayscompute#globalVmExtensionPolicy for globalVmExtensionPolicies.
    public var kind: Swift.String? = nil

    /// Name of the resource. Provided by the client when the resource is created.
    /// The name must be 1-63 characters long, and comply withRFC1035.
    /// Specifically, the name must be 1-63 characters long and match the regular
    /// expression `[a-z]([-a-z0-9]*[a-z0-9])?`
    /// which means the first character must be a lowercase letter, and all
    /// following characters must be a dash, lowercase letter, or digit, except
    /// the last character, which cannot be a dash.
    public var name: Swift.String? = nil

    /// Optional. Used to resolve conflicts when multiple policies are active for the same
    /// extension. Defaults to 0.
    ///
    /// Larger the number, higher the priority. When the priority is the same,
    /// the policy with the newer create time has higher priority.
    public var priority: Swift.Int32? = nil

    /// Required. The rollout strategy and status.
    public var rolloutOperation: GlobalVmExtensionPolicyRolloutOperation? = nil

    /// Output only. [Output Only] The scoped resource status. It's only for tracking the
    /// purging status of the policy.
    public var scopedResourceStatus: GlobalVmExtensionPolicy.ScopedResourceStatus? = nil

    /// Output only. [Output Only] Server-defined fully-qualified URL for this resource.
    public var selfLink: Swift.String? = nil

    /// Output only. [Output Only] Server-defined URL for this resource's resource id.
    public var selfLinkWithId: Swift.String? = nil

    /// Output only. [Output Only] Update timestamp inRFC3339
    /// text format.
    public var updateTimestamp: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GlobalVmExtensionPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GlobalVmExtensionPolicy().with { $0.creationTimestamp = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let creationTimestamp = CodingKeys(stringValue: "creationTimestamp")
      static let description = CodingKeys(stringValue: "description")
      static let extensionPolicies = CodingKeys(stringValue: "extensionPolicies")
      static let id = CodingKeys(stringValue: "id")
      static let instanceSelectors = CodingKeys(stringValue: "instanceSelectors")
      static let kind = CodingKeys(stringValue: "kind")
      static let name = CodingKeys(stringValue: "name")
      static let priority = CodingKeys(stringValue: "priority")
      static let rolloutOperation = CodingKeys(stringValue: "rolloutOperation")
      static let scopedResourceStatus = CodingKeys(stringValue: "scopedResourceStatus")
      static let selfLink = CodingKeys(stringValue: "selfLink")
      static let selfLinkWithId = CodingKeys(stringValue: "selfLinkWithId")
      static let updateTimestamp = CodingKeys(stringValue: "updateTimestamp")

      static let _knownKeys: Set<Swift.String> = [
        "creationTimestamp",
        "description",
        "extensionPolicies",
        "id",
        "instanceSelectors",
        "kind",
        "name",
        "priority",
        "rolloutOperation",
        "scopedResourceStatus",
        "selfLink",
        "selfLinkWithId",
        "updateTimestamp",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.creationTimestamp = try container.decodeIfPresent(
        Swift.String.self, forKey: .creationTimestamp)
      self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
      if let value = try container.decodeIfPresent(
        [Swift.String: GlobalVmExtensionPolicyExtensionPolicy].self, forKey: .extensionPolicies)
      {
        self.extensionPolicies = value
      }
      self.id = try container.decodeIfPresent(Swift.UInt64.self, forKey: .id)
      if let value = try container.decodeIfPresent(
        [GlobalVmExtensionPolicyInstanceSelector].self, forKey: .instanceSelectors)
      {
        self.instanceSelectors = value
      }
      self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
      self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
      self.priority = try container.decodeIfPresent(Swift.Int32.self, forKey: .priority)
      self.rolloutOperation = try container.decodeIfPresent(
        GlobalVmExtensionPolicyRolloutOperation.self, forKey: .rolloutOperation)
      self.scopedResourceStatus = try container.decodeIfPresent(
        GlobalVmExtensionPolicy.ScopedResourceStatus.self, forKey: .scopedResourceStatus)
      self.selfLink = try container.decodeIfPresent(Swift.String.self, forKey: .selfLink)
      self.selfLinkWithId = try container.decodeIfPresent(
        Swift.String.self, forKey: .selfLinkWithId)
      self.updateTimestamp = try container.decodeIfPresent(
        Swift.String.self, forKey: .updateTimestamp)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.creationTimestamp, forKey: .creationTimestamp)
      try container.encodeIfPresent(self.description, forKey: .description)
      try container.encode(self.extensionPolicies, forKey: .extensionPolicies)
      try container.encodeIfPresent(self.id, forKey: .id)
      try container.encode(self.instanceSelectors, forKey: .instanceSelectors)
      try container.encodeIfPresent(self.kind, forKey: .kind)
      try container.encodeIfPresent(self.name, forKey: .name)
      try container.encodeIfPresent(self.priority, forKey: .priority)
      try container.encodeIfPresent(self.rolloutOperation, forKey: .rolloutOperation)
      try container.encodeIfPresent(self.scopedResourceStatus, forKey: .scopedResourceStatus)
      try container.encodeIfPresent(self.selfLink, forKey: .selfLink)
      try container.encodeIfPresent(self.selfLinkWithId, forKey: .selfLinkWithId)
      try container.encodeIfPresent(self.updateTimestamp, forKey: .updateTimestamp)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [scopedResourceStatus][google.cloud.compute.v1.GlobalVmExtensionPolicy.scopedResourceStatus] field.
    ///
    /// [google.cloud.compute.v1.GlobalVmExtensionPolicy.scopedResourceStatus]: <doc:GlobalVmExtensionPolicy/ScopedResourceStatus>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ScopedResourceStatus: Codable, Equatable, Hashable, Sendable {
      /// The zonal policies are being deleted.
      case deleting
      /// Default value. This value is unused.
      case unspecified
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String {
        switch self {
        case .deleting: return "SCOPED_RESOURCE_STATUS_DELETING"
        case .unspecified: return "SCOPED_RESOURCE_STATUS_UNSPECIFIED"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ScopedResourceStatus/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SCOPED_RESOURCE_STATUS_DELETING": self = .deleting
        case "SCOPED_RESOURCE_STATUS_UNSPECIFIED": self = .unspecified
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .deleting: return try container.encode("SCOPED_RESOURCE_STATUS_DELETING")
        case .unspecified: return try container.encode("SCOPED_RESOURCE_STATUS_UNSPECIFIED")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.GlobalVmExtensionPolicy"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
