// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GlobalFrontendSettings
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Represents the Global Frontend Bundle settings for a single project.
  public struct GlobalFrontendSettings: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Customer-settable bundle type.
    public var bundleType: GlobalFrontendSettings.BundleType? = nil

    /// Output only. [Output Only] Creation timestamp in RFC3339 text format.
    public var creationTimestamp: Swift.String? = nil

    /// Output only. [Output Only] An optional description of this resource.
    public var description: Swift.String? = nil

    /// Output only. For optimistic locking.
    public var etag: Swift.String? = nil

    /// Output only. [Output Only] The unique identifier for the resource. This identifier is
    /// defined by the server.
    public var id: Swift.UInt64? = nil

    /// Output only. OUTPUT_ONLY fields
    /// [Output Only] Name of the resource. Must be 1-63 characters long and match
    /// the regular expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first
    /// character must be a lowercase letter, and all following characters must
    /// be a dash, lowercase letter, or digit, except the last character, which
    /// cannot be a dash.
    public var name: Swift.String? = nil

    /// Output only. [Output Only] Server-defined URL for the resource.
    public var selfLink: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GlobalFrontendSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GlobalFrontendSettings().with { $0.bundleType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let bundleType = CodingKeys(stringValue: "bundleType")
      static let creationTimestamp = CodingKeys(stringValue: "creationTimestamp")
      static let description = CodingKeys(stringValue: "description")
      static let etag = CodingKeys(stringValue: "etag")
      static let id = CodingKeys(stringValue: "id")
      static let name = CodingKeys(stringValue: "name")
      static let selfLink = CodingKeys(stringValue: "selfLink")

      static let _knownKeys: Set<Swift.String> = [
        "bundleType",
        "creationTimestamp",
        "description",
        "etag",
        "id",
        "name",
        "selfLink",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.bundleType = try container.decodeIfPresent(
        GlobalFrontendSettings.BundleType.self, forKey: .bundleType)
      self.creationTimestamp = try container.decodeIfPresent(
        Swift.String.self, forKey: .creationTimestamp)
      self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
      self.etag = try container.decodeIfPresent(Swift.String.self, forKey: .etag)
      self.id = try container.decodeIfPresent(Swift.UInt64.self, forKey: .id)
      self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
      self.selfLink = try container.decodeIfPresent(Swift.String.self, forKey: .selfLink)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.bundleType, forKey: .bundleType)
      try container.encodeIfPresent(self.creationTimestamp, forKey: .creationTimestamp)
      try container.encodeIfPresent(self.description, forKey: .description)
      try container.encodeIfPresent(self.etag, forKey: .etag)
      try container.encodeIfPresent(self.id, forKey: .id)
      try container.encodeIfPresent(self.name, forKey: .name)
      try container.encodeIfPresent(self.selfLink, forKey: .selfLink)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [bundleType][google.cloud.compute.v1.GlobalFrontendSettings.bundleType] field.
    ///
    /// [google.cloud.compute.v1.GlobalFrontendSettings.bundleType]: <doc:GlobalFrontendSettings/BundleType>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum BundleType: Codable, Equatable, Hashable, Sendable {
      /// Bundling is not active.
      case unspecified
      /// Standard Global Frontend bundle.
      case globalFrontEnd
      /// Ala Carte mode.
      case individual
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String {
        switch self {
        case .unspecified: return "BUNDLE_TYPE_UNSPECIFIED"
        case .globalFrontEnd: return "GLOBAL_FRONT_END"
        case .individual: return "INDIVIDUAL"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BundleType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "BUNDLE_TYPE_UNSPECIFIED": self = .unspecified
        case "GLOBAL_FRONT_END": self = .globalFrontEnd
        case "INDIVIDUAL": self = .individual
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: any Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: any Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("BUNDLE_TYPE_UNSPECIFIED")
        case .globalFrontEnd: return try container.encode("GLOBAL_FRONT_END")
        case .individual: return try container.encode("INDIVIDUAL")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type URL for `GlobalFrontendSettings`: `"type.googleapis.com/google.cloud.compute.v1.GlobalFrontendSettings"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.GlobalFrontendSettings"
    }

    /// Initialize an instance of `GlobalFrontendSettings` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.compute.v1.GlobalFrontendSettings"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `GlobalFrontendSettings` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
