// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GlobalNetworkEndpointGroups
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  extension Clients {
    final class GlobalNetworkEndpointGroupsRetry: GlobalNetworkEndpointGroupsStub {
      let inner: any GlobalNetworkEndpointGroupsStub
      let options: GoogleCloudGax.ClientOptions

      public init(
        _ inner: any GlobalNetworkEndpointGroupsStub, options: GoogleCloudGax.ClientOptions
      ) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func attachNetworkEndpoints(
        request: GlobalNetworkEndpointGroupsClient.AttachNetworkEndpointsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (
              r: GlobalNetworkEndpointGroupsClient.AttachNetworkEndpointsRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.attachNetworkEndpoints(request: r, options: o)
          })
      }

      public func delete(
        request: GlobalNetworkEndpointGroupsClient.DeleteRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GlobalNetworkEndpointGroupsClient.DeleteRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func detachNetworkEndpoints(
        request: GlobalNetworkEndpointGroupsClient.DetachNetworkEndpointsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (
              r: GlobalNetworkEndpointGroupsClient.DetachNetworkEndpointsRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.detachNetworkEndpoints(request: r, options: o)
          })
      }

      public func `get`(
        request: GlobalNetworkEndpointGroupsClient.GetRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NetworkEndpointGroup {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GlobalNetworkEndpointGroupsClient.GetRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.NetworkEndpointGroup
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func insert(
        request: GlobalNetworkEndpointGroupsClient.InsertRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GlobalNetworkEndpointGroupsClient.InsertRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: GlobalNetworkEndpointGroupsClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NetworkEndpointGroupList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GlobalNetworkEndpointGroupsClient.ListRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.NetworkEndpointGroupList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func listNetworkEndpoints(
        request: GlobalNetworkEndpointGroupsClient.ListNetworkEndpointsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NetworkEndpointGroupsListNetworkEndpoints {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (
              r: GlobalNetworkEndpointGroupsClient.ListNetworkEndpointsRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.NetworkEndpointGroupsListNetworkEndpoints
            in
            return try await self.inner.listNetworkEndpoints(request: r, options: o)
          })
      }
    }
  }
#endif
