// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GlobalOrganizationOperations
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service for the `globalOrganizationOperations` resource.
  ///
  /// @Snippet(path: "globalOrganizationOperationsQuickstart")
  public protocol GlobalOrganizationOperations {
    /// Deletes the specified Operations resource.
    ///
    /// @Snippet(path: "globalOrganizationOperations_delete")
    func delete(request: Clients.GlobalOrganizationOperationsClient.DeleteRequest) async throws

    /// Deletes the specified Operations resource.
    func delete(
      operation: Swift.String,
    ) async throws

    /// Retrieves the specified Operations resource. Gets a list of operations
    /// by making a `list()` request.
    ///
    /// @Snippet(path: "globalOrganizationOperations_get")
    func `get`(request: Clients.GlobalOrganizationOperationsClient.GetRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Retrieves the specified Operations resource. Gets a list of operations
    /// by making a `list()` request.
    func `get`(
      operation: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Retrieves a list of Operation resources contained within the specified
    /// organization.
    ///
    /// @Snippet(path: "globalOrganizationOperations_list")
    func list(request: Clients.GlobalOrganizationOperationsClient.ListRequest) async throws
      -> GoogleCloudComputeV1.OperationList

    /// Retrieves a list of Operation resources contained within the specified
    /// organization.
    func list(
      byItem: Clients.GlobalOrganizationOperationsClient.ListRequest
    ) throws -> any AsyncSequence<Operation, Swift.Error>

    /// Retrieves a list of Operation resources contained within the specified
    /// organization.
    func list() throws -> any AsyncSequence<Operation, Swift.Error>

    /// Deletes the specified Operations resource.
    ///
    /// @Snippet(path: "globalOrganizationOperations_delete")
    func delete(
      request: Clients.GlobalOrganizationOperationsClient.DeleteRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws

    /// Retrieves the specified Operations resource. Gets a list of operations
    /// by making a `list()` request.
    ///
    /// @Snippet(path: "globalOrganizationOperations_get")
    func `get`(
      request: Clients.GlobalOrganizationOperationsClient.GetRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Retrieves a list of Operation resources contained within the specified
    /// organization.
    ///
    /// @Snippet(path: "globalOrganizationOperations_list")
    func list(
      request: Clients.GlobalOrganizationOperationsClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.OperationList

    /// Retrieves a list of Operation resources contained within the specified
    /// organization.
    func list(
      byItem: Clients.GlobalOrganizationOperationsClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Operation, Swift.Error>
  }

  extension Clients {
    /// The recommended implementation for ``GlobalOrganizationOperations``.
    public class GlobalOrganizationOperationsClient: GlobalOrganizationOperations {
      let inner: any GlobalOrganizationOperationsStub

      /// Creates a new `GlobalOrganizationOperationsClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any GlobalOrganizationOperationsStub = try GlobalOrganizationOperationsTransport(
          options)
        inner = GlobalOrganizationOperationsRetry(inner, options: options)
        if let logger = options.logger {
          inner = GlobalOrganizationOperationsLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `GlobalOrganizationOperations.delete`
      public func delete(
        request: Clients.GlobalOrganizationOperationsClient.DeleteRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self.inner.delete(request: request, options: options)
      }

      /// See `GlobalOrganizationOperations.`get``
      public func `get`(
        request: Clients.GlobalOrganizationOperationsClient.GetRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.`get`(request: request, options: options)
      }

      /// See `GlobalOrganizationOperations.list`
      public func list(
        request: Clients.GlobalOrganizationOperationsClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.OperationList {
        try await self.inner.list(request: request, options: options)
      }

      /// Retrieves a list of Operation resources contained within the specified
      /// organization.
      public func list(
        byItem: Clients.GlobalOrganizationOperationsClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<Operation, Swift.Error> {
        let listRpc = { (token: String) async throws -> GoogleCloudComputeV1.OperationList in
          var request = byItem
          request.pageToken = token
          return try await self.list(request: request, options: options)
        }
        return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
      }
    }
  }

  // Default implementations
  extension GlobalOrganizationOperations {
    public func delete(request: Clients.GlobalOrganizationOperationsClient.DeleteRequest)
      async throws
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: Clients.GlobalOrganizationOperationsClient.DeleteRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func delete(
      operation: Swift.String,
    ) async throws {
      let request = Clients.GlobalOrganizationOperationsClient.DeleteRequest().with {
        $0.operation = operation
      }
      try await self.delete(request: request)
    }

    public func `get`(request: Clients.GlobalOrganizationOperationsClient.GetRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: Clients.GlobalOrganizationOperationsClient.GetRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func `get`(
      operation: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.GlobalOrganizationOperationsClient.GetRequest().with {
        $0.operation = operation
      }
      return try await self.`get`(request: request)
    }

    public func list(request: Clients.GlobalOrganizationOperationsClient.ListRequest) async throws
      -> GoogleCloudComputeV1.OperationList
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: Clients.GlobalOrganizationOperationsClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.OperationList {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(
      byItem: Clients.GlobalOrganizationOperationsClient.ListRequest
    ) throws -> any AsyncSequence<Operation, Swift.Error> {
      try self.list(byItem: byItem, options: .init())
    }

    public func list(
      byItem: Clients.GlobalOrganizationOperationsClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudComputeV1.OperationList in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func list() throws -> any AsyncSequence<Operation, Swift.Error> {
      let request = Clients.GlobalOrganizationOperationsClient.ListRequest().with {
      }
      return try self.list(byItem: request)
    }
  }
#endif
