// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if RegionHealthAggregationPolicies
  public import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Represents a health aggregation policy.
  ///
  /// A health aggregation policy resource defines a policy to aggregate health.
  ///
  /// For more information, see
  /// Health checks overview.
  public struct HealthAggregationPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. [Output Only] Creation timestamp inRFC3339
    /// text format.
    public var creationTimestamp: Swift.String? = nil

    /// An optional description of this resource. Provide this property when you
    /// create the resource.
    public var description: Swift.String? = nil

    /// Fingerprint of this resource. A hash of the contents stored in this object.
    /// This field is used in optimistic locking. This field will be ignored when
    /// inserting a HealthAggregationPolicy. An up-to-date fingerprint
    /// must be provided in order to patch the HealthAggregationPolicy; Otherwise,
    /// the request will fail with error 412 conditionNotMet. To see
    /// the latest fingerprint, make a get() request to retrieve the
    /// HealthAggregationPolicy.
    public var fingerprint: Foundation.Data? = nil

    /// Can only be set if the policyType field isBACKEND_SERVICE_POLICY. Specifies the threshold (as a
    /// percentage) of healthy endpoints required in order to consider the
    /// aggregated health result HEALTHY. Defaults to 60. Must be in
    /// range [0, 100]. Not applicable if the policyType field isDNB_PUBLIC_IP_POLICY. Can be mutated. This field is optional,
    /// and will be set to the default if unspecified. Note that both this
    /// threshold and minHealthyThreshold must be satisfied in order
    /// for HEALTHY to be the aggregated result. "Endpoints" refers to network
    /// endpoints within a Network Endpoint Group or instances within an Instance
    /// Group.
    public var healthyPercentThreshold: Swift.UInt32? = nil

    /// Output only. [Output Only] The unique identifier for the resource. This identifier is
    /// defined by the server.
    public var id: Swift.UInt64? = nil

    /// Output only. [Output Only] Type of the resource. Alwayscompute#healthAggregationPolicy for health aggregation
    /// policies.
    public var kind: Swift.String? = nil

    /// Can only be set if the policyType field isBACKEND_SERVICE_POLICY. Specifies the minimum number of
    /// healthy endpoints required in order to consider the aggregated health
    /// result HEALTHY. Defaults to 1. Must be positive. Not
    /// applicable if the policyType field isDNB_PUBLIC_IP_POLICY. Can be mutated. This field is optional,
    /// and will be set to the default if unspecified. Note that both this
    /// threshold and healthyPercentThreshold must be satisfied in
    /// order for HEALTHY to be the aggregated result. "Endpoints" refers to
    /// network endpoints within a Network Endpoint Group or instances within an
    /// Instance Group.
    public var minHealthyThreshold: Swift.UInt32? = nil

    /// Name of the resource. Provided by the client when the resource is created.
    /// The name must be 1-63 characters long, and comply withRFC1035.
    /// Specifically, the name must be 1-63 characters long and match the regular
    /// expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first
    /// character must be a lowercase letter, and all following characters must
    /// be a dash, lowercase letter, or digit, except the last character, which
    /// cannot be a dash.
    public var name: Swift.String? = nil

    /// Specifies the type of the healthAggregationPolicy. The only allowed value
    /// for global resources is DNS_PUBLIC_IP_POLICY. The only allowed
    /// value for regional resources is BACKEND_SERVICE_POLICY. Must
    /// be specified when the healthAggregationPolicy is created, and cannot be
    /// mutated.
    public var policyType: HealthAggregationPolicy.PolicyType? = nil

    /// Output only. [Output Only] URL of the region where the health aggregation policy
    /// resides. This field applies only to the regional resource. You must specify
    /// this field as part of the HTTP request URL. It is not settable as a field
    /// in the request body.
    public var region: Swift.String? = nil

    /// Output only. [Output Only] Server-defined URL for the resource.
    public var selfLink: Swift.String? = nil

    /// Output only. [Output Only] Server-defined URL with id for the resource.
    public var selfLinkWithId: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `HealthAggregationPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = HealthAggregationPolicy().with { $0.creationTimestamp = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let creationTimestamp = CodingKeys(stringValue: "creationTimestamp")
      static let description = CodingKeys(stringValue: "description")
      static let fingerprint = CodingKeys(stringValue: "fingerprint")
      static let healthyPercentThreshold = CodingKeys(stringValue: "healthyPercentThreshold")
      static let id = CodingKeys(stringValue: "id")
      static let kind = CodingKeys(stringValue: "kind")
      static let minHealthyThreshold = CodingKeys(stringValue: "minHealthyThreshold")
      static let name = CodingKeys(stringValue: "name")
      static let policyType = CodingKeys(stringValue: "policyType")
      static let region = CodingKeys(stringValue: "region")
      static let selfLink = CodingKeys(stringValue: "selfLink")
      static let selfLinkWithId = CodingKeys(stringValue: "selfLinkWithId")

      static let _knownKeys: Set<Swift.String> = [
        "creationTimestamp",
        "description",
        "fingerprint",
        "healthyPercentThreshold",
        "id",
        "kind",
        "minHealthyThreshold",
        "name",
        "policyType",
        "region",
        "selfLink",
        "selfLinkWithId",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.creationTimestamp = try container.decodeIfPresent(
        Swift.String.self, forKey: .creationTimestamp)
      self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
      if let s = try container.decodeIfPresent(Swift.String.self, forKey: .fingerprint) {
        guard let v = GoogleWKT._DiscoveryBase64.decode(s) else {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath, debugDescription: "Expected url-safe encoded value")
          )
        }
        self.fingerprint = v
      }
      self.healthyPercentThreshold = try container.decodeIfPresent(
        Swift.UInt32.self, forKey: .healthyPercentThreshold)
      self.id = try container.decodeIfPresent(Swift.UInt64.self, forKey: .id)
      self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
      self.minHealthyThreshold = try container.decodeIfPresent(
        Swift.UInt32.self, forKey: .minHealthyThreshold)
      self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
      self.policyType = try container.decodeIfPresent(
        HealthAggregationPolicy.PolicyType.self, forKey: .policyType)
      self.region = try container.decodeIfPresent(Swift.String.self, forKey: .region)
      self.selfLink = try container.decodeIfPresent(Swift.String.self, forKey: .selfLink)
      self.selfLinkWithId = try container.decodeIfPresent(
        Swift.String.self, forKey: .selfLinkWithId)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.creationTimestamp, forKey: .creationTimestamp)
      try container.encodeIfPresent(self.description, forKey: .description)
      if let v = fingerprint {
        try container.encode(
          GoogleWKT._DiscoveryBase64.encode(v), forKey: .fingerprint
        )
      }
      try container.encodeIfPresent(self.healthyPercentThreshold, forKey: .healthyPercentThreshold)
      try container.encodeIfPresent(self.id, forKey: .id)
      try container.encodeIfPresent(self.kind, forKey: .kind)
      try container.encodeIfPresent(self.minHealthyThreshold, forKey: .minHealthyThreshold)
      try container.encodeIfPresent(self.name, forKey: .name)
      try container.encodeIfPresent(self.policyType, forKey: .policyType)
      try container.encodeIfPresent(self.region, forKey: .region)
      try container.encodeIfPresent(self.selfLink, forKey: .selfLink)
      try container.encodeIfPresent(self.selfLinkWithId, forKey: .selfLinkWithId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [policyType][google.cloud.compute.v1.HealthAggregationPolicy.policyType] field.
    ///
    /// [google.cloud.compute.v1.HealthAggregationPolicy.policyType]: <doc:HealthAggregationPolicy/PolicyType>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum PolicyType: Codable, Equatable, Sendable {
      case backendServicePolicy
      case dnsPublicIpPolicy
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .backendServicePolicy: return "BACKEND_SERVICE_POLICY"
        case .dnsPublicIpPolicy: return "DNS_PUBLIC_IP_POLICY"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PolicyType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "BACKEND_SERVICE_POLICY": self = .backendServicePolicy
        case "DNS_PUBLIC_IP_POLICY": self = .dnsPublicIpPolicy
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .backendServicePolicy: return try container.encode("BACKEND_SERVICE_POLICY")
        case .dnsPublicIpPolicy: return try container.encode("DNS_PUBLIC_IP_POLICY")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.HealthAggregationPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
