// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Images
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  extension Clients {
    final class ImagesRetry: ImagesStub {
      let inner: any ImagesStub
      let options: GoogleCloudGax.ClientOptions

      public init(_ inner: any ImagesStub, options: GoogleCloudGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func delete(
        request: Clients.ImagesClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.ImagesClient.DeleteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func deprecate(
        request: Clients.ImagesClient.DeprecateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.ImagesClient.DeprecateRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.deprecate(request: r, options: o)
          })
      }

      public func `get`(
        request: Clients.ImagesClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Image {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: Clients.ImagesClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Image
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func getFromFamily(
        request: Clients.ImagesClient.GetFromFamilyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Image {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: Clients.ImagesClient.GetFromFamilyRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Image
            in
            return try await self.inner.getFromFamily(request: r, options: o)
          })
      }

      public func getIamPolicy(
        request: Clients.ImagesClient.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: Clients.ImagesClient.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Policy
            in
            return try await self.inner.getIamPolicy(request: r, options: o)
          })
      }

      public func insert(
        request: Clients.ImagesClient.InsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.ImagesClient.InsertRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: Clients.ImagesClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.ImageList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: Clients.ImagesClient.ListRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.ImageList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func patch(
        request: Clients.ImagesClient.PatchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.ImagesClient.PatchRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.patch(request: r, options: o)
          })
      }

      public func setIamPolicy(
        request: Clients.ImagesClient.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.ImagesClient.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Policy
            in
            return try await self.inner.setIamPolicy(request: r, options: o)
          })
      }

      public func setLabels(
        request: Clients.ImagesClient.SetLabelsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.ImagesClient.SetLabelsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.setLabels(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: Clients.ImagesClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.ImagesClient.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.TestPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }
    }
  }
#endif
