// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Projects
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  public struct InstanceMoveRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The URL of the destination zone to move the instance. This can be a full or
    /// partial URL. For example, the following are all valid URLs to a zone:
    ///
    ///    - https://www.googleapis.com/compute/v1/projects/project/zones/zone
    ///    - projects/project/zones/zone
    ///    - zones/zone
    public var destinationZone: Swift.String? = nil

    /// The URL of the target instance to move. This can be a full or partial URL.
    /// For example, the following are all valid URLs to an instance:
    ///
    ///    - https://www.googleapis.com/compute/v1/projects/project/zones/zone/instances/instance
    ///    - projects/project/zones/zone/instances/instance
    ///    - zones/zone/instances/instance
    public var targetInstance: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InstanceMoveRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InstanceMoveRequest().with { $0.destinationZone = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let destinationZone = CodingKeys(stringValue: "destinationZone")
      static let targetInstance = CodingKeys(stringValue: "targetInstance")

      static let _knownKeys: Set<Swift.String> = [
        "destinationZone",
        "targetInstance",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.destinationZone = try container.decodeIfPresent(
        Swift.String.self, forKey: .destinationZone)
      self.targetInstance = try container.decodeIfPresent(
        Swift.String.self, forKey: .targetInstance)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.destinationZone, forKey: .destinationZone)
      try container.encodeIfPresent(self.targetInstance, forKey: .targetInstance)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.InstanceMoveRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
