// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if InstanceGroups
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleCloudGax
  import struct Logging.Logger

  extension Clients {
    final class InstanceGroupsLogging: InstanceGroupsStub {
      let inner: any InstanceGroupsStub
      let logger: Logger

      public init(_ inner: any InstanceGroupsStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudComputeV1"
        logger[metadataKey: "gcp.client.service"] = "compute"
        logger[metadataKey: "gcp.experimental.swift.client"] = "InstanceGroups"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        name: String,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func addInstances(
        request: InstanceGroupsClient.AddInstancesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "addInstances",
          action: {
            (r: InstanceGroupsClient.AddInstancesRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.addInstances(request: r, options: o)
          })
      }

      public func aggregatedList(
        request: InstanceGroupsClient.AggregatedListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.InstanceGroupAggregatedList {
        try await self._intercept(
          request: request,
          options: options,
          name: "aggregatedList",
          action: {
            (r: InstanceGroupsClient.AggregatedListRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.InstanceGroupAggregatedList
            in
            return try await self.inner.aggregatedList(request: r, options: o)
          })
      }

      public func delete(
        request: InstanceGroupsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "delete",
          action: {
            (r: InstanceGroupsClient.DeleteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func `get`(
        request: InstanceGroupsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.InstanceGroup {
        try await self._intercept(
          request: request,
          options: options,
          name: "`get`",
          action: {
            (r: InstanceGroupsClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.InstanceGroup
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func insert(
        request: InstanceGroupsClient.InsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "insert",
          action: {
            (r: InstanceGroupsClient.InsertRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: InstanceGroupsClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.InstanceGroupList {
        try await self._intercept(
          request: request,
          options: options,
          name: "list",
          action: {
            (r: InstanceGroupsClient.ListRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.InstanceGroupList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func listInstances(
        request: InstanceGroupsClient.ListInstancesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.InstanceGroupsListInstances {
        try await self._intercept(
          request: request,
          options: options,
          name: "listInstances",
          action: {
            (r: InstanceGroupsClient.ListInstancesRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.InstanceGroupsListInstances
            in
            return try await self.inner.listInstances(request: r, options: o)
          })
      }

      public func removeInstances(
        request: InstanceGroupsClient.RemoveInstancesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "removeInstances",
          action: {
            (r: InstanceGroupsClient.RemoveInstancesRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.removeInstances(request: r, options: o)
          })
      }

      public func setNamedPorts(
        request: InstanceGroupsClient.SetNamedPortsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "setNamedPorts",
          action: {
            (r: InstanceGroupsClient.SetNamedPortsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.setNamedPorts(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: InstanceGroupsClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "testIamPermissions",
          action: {
            (r: InstanceGroupsClient.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.TestPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }

      public func getOperation(
        request: ZoneOperationsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "getOperation",
          action: {
            (r: ZoneOperationsClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }
    }
  }
#endif
