// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if InterconnectAttachments
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  extension Clients {
    final class InterconnectAttachmentsLogging: InterconnectAttachmentsStub {
      let inner: any InterconnectAttachmentsStub
      let logger: Logging.Logger

      public init(_ inner: any InterconnectAttachmentsStub, logger: Logging.Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudComputeV1"
        logger[metadataKey: "gcp.client.service"] = "compute"
        logger[metadataKey: "gcp.experimental.swift.client"] = "InterconnectAttachments"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        name: String,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func aggregatedList(
        request: Clients.InterconnectAttachmentsClient.AggregatedListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.InterconnectAttachmentAggregatedList {
        try await self._intercept(
          request: request,
          options: options,
          name: "aggregatedList",
          action: {
            (
              r: Clients.InterconnectAttachmentsClient.AggregatedListRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.InterconnectAttachmentAggregatedList
            in
            return try await self.inner.aggregatedList(request: r, options: o)
          })
      }

      public func delete(
        request: Clients.InterconnectAttachmentsClient.DeleteRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "delete",
          action: {
            (
              r: Clients.InterconnectAttachmentsClient.DeleteRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func `get`(
        request: Clients.InterconnectAttachmentsClient.GetRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.InterconnectAttachment {
        try await self._intercept(
          request: request,
          options: options,
          name: "`get`",
          action: {
            (r: Clients.InterconnectAttachmentsClient.GetRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.InterconnectAttachment
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func insert(
        request: Clients.InterconnectAttachmentsClient.InsertRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "insert",
          action: {
            (
              r: Clients.InterconnectAttachmentsClient.InsertRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: Clients.InterconnectAttachmentsClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.InterconnectAttachmentList {
        try await self._intercept(
          request: request,
          options: options,
          name: "list",
          action: {
            (r: Clients.InterconnectAttachmentsClient.ListRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.InterconnectAttachmentList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func patch(
        request: Clients.InterconnectAttachmentsClient.PatchRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "patch",
          action: {
            (
              r: Clients.InterconnectAttachmentsClient.PatchRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.patch(request: r, options: o)
          })
      }

      public func setLabels(
        request: Clients.InterconnectAttachmentsClient.SetLabelsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "setLabels",
          action: {
            (
              r: Clients.InterconnectAttachmentsClient.SetLabelsRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.setLabels(request: r, options: o)
          })
      }
    }
  }
#endif
