// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if InterconnectGroups || Interconnects
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  public struct InterconnectDiagnosticsLinkOpticalPower: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The status of the current value when compared to the warning and alarm
    /// levels for the receiving or transmitting transceiver. Possible states
    /// include:
    ///
    ///
    ///     - OK: The value has not crossed a warning threshold.
    ///     - LOW_WARNING: The value has crossed below the low
    ///     warning threshold.
    ///    - HIGH_WARNING: The value has
    ///     crossed above the high warning threshold.
    ///     - LOW_ALARM: The value has crossed below the low alarm
    ///     threshold.
    ///     - HIGH_ALARM: The value has crossed above the high alarm
    ///     threshold.
    public var state: InterconnectDiagnosticsLinkOpticalPower.State? = nil

    /// Value of the current receiving or transmitting optical power, read in
    /// dBm. Take a known good optical value, give it a 10% margin and trigger
    /// warnings relative to that value. In general, a -7dBm warning and a -11dBm
    /// alarm are good optical value estimates for most links.
    public var value: Swift.Float? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InterconnectDiagnosticsLinkOpticalPower`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InterconnectDiagnosticsLinkOpticalPower().with { $0.state = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let state = CodingKeys(stringValue: "state")
      static let value = CodingKeys(stringValue: "value")

      static let _knownKeys: Set<Swift.String> = [
        "state",
        "value",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.state = try container.decodeIfPresent(
        InterconnectDiagnosticsLinkOpticalPower.State.self, forKey: .state)
      self.value = try container.decodeIfPresent(Swift.Float.self, forKey: .value)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.state, forKey: .state)
      try container.encodeIfPresent(self.value, forKey: .value)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [state][google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower.state] field.
    ///
    /// [google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower.state]: <doc:InterconnectDiagnosticsLinkOpticalPower/State>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum State: Codable, Equatable, Hashable, Sendable {
      /// The value has crossed above the high alarm threshold.
      case highAlarm
      /// The value of the current optical power has crossed above the high
      /// warning threshold.
      case highWarning
      /// The value of the current optical power has crossed below the low alarm
      /// threshold.
      case lowAlarm
      /// The value of the current optical power has crossed below the low
      /// warning threshold.
      case lowWarning
      /// The value of the current optical power has not crossed a warning
      /// threshold.
      case ok
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String {
        switch self {
        case .highAlarm: return "HIGH_ALARM"
        case .highWarning: return "HIGH_WARNING"
        case .lowAlarm: return "LOW_ALARM"
        case .lowWarning: return "LOW_WARNING"
        case .ok: return "OK"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "HIGH_ALARM": self = .highAlarm
        case "HIGH_WARNING": self = .highWarning
        case "LOW_ALARM": self = .lowAlarm
        case "LOW_WARNING": self = .lowWarning
        case "OK": self = .ok
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .highAlarm: return try container.encode("HIGH_ALARM")
        case .highWarning: return try container.encode("HIGH_WARNING")
        case .lowAlarm: return try container.encode("LOW_ALARM")
        case .lowWarning: return try container.encode("LOW_WARNING")
        case .ok: return try container.encode("OK")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.InterconnectDiagnosticsLinkOpticalPower"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
