// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if InterconnectAttachments
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Informational metadata about Partner attachments from Partners to display
  /// to customers.  These fields are propagated from PARTNER_PROVIDER
  /// attachments to their corresponding PARTNER attachments.
  public struct InterconnectAttachmentPartnerMetadata: Codable, Equatable, GoogleCloudWKT
      ._AnyPackable,
    Sendable
  {
    /// Plain text name of the Interconnect this attachment is connected to, as
    /// displayed in the Partner's portal. For instance "Chicago 1".
    /// This value may be validated to match approved Partner values.
    public var interconnectName: Swift.String? = nil

    /// Plain text name of the Partner providing this attachment.
    /// This value may be validated to match approved Partner values.
    public var partnerName: Swift.String? = nil

    /// URL of the Partner's portal for this Attachment. Partners may customise
    /// this to be a deep link to the specific resource on the Partner portal.
    /// This value may be validated to match approved Partner values.
    public var portalUrl: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `InterconnectAttachmentPartnerMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InterconnectAttachmentPartnerMetadata().with { $0.interconnectName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let interconnectName = CodingKeys(stringValue: "interconnectName")
      static let partnerName = CodingKeys(stringValue: "partnerName")
      static let portalUrl = CodingKeys(stringValue: "portalUrl")

      static let _knownKeys: Set<Swift.String> = [
        "interconnectName",
        "partnerName",
        "portalUrl",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.interconnectName = try container.decodeIfPresent(
        Swift.String.self, forKey: .interconnectName)
      self.partnerName = try container.decodeIfPresent(Swift.String.self, forKey: .partnerName)
      self.portalUrl = try container.decodeIfPresent(Swift.String.self, forKey: .portalUrl)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.interconnectName, forKey: .interconnectName)
      try container.encodeIfPresent(self.partnerName, forKey: .partnerName)
      try container.encodeIfPresent(self.portalUrl, forKey: .portalUrl)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.InterconnectAttachmentPartnerMetadata"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
