// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if InterconnectRemoteLocations
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  public struct InterconnectRemoteLocationConstraints: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. [Output Only] Port pair remote location constraints, which can take one
    /// of the following values: PORT_PAIR_UNCONSTRAINED_REMOTE_LOCATION,
    /// PORT_PAIR_MATCHING_REMOTE_LOCATION.
    ///
    /// Google Cloud API refers only to individual ports, but the UI uses this
    /// field when ordering a pair of ports, to prevent users from accidentally
    /// ordering something that is incompatible with their cloud provider.
    /// Specifically, when ordering a redundant pair of Cross-Cloud Interconnect
    /// ports, and one of them uses a remote location with
    /// portPairMatchingRemoteLocation set to matching, the UI requires that
    /// both ports use the same remote location.
    public var portPairRemoteLocation:
      InterconnectRemoteLocationConstraints.PortPairRemoteLocation? = nil

    /// Output only. [Output Only] Port pair VLAN constraints, which can take one of the
    /// following values: PORT_PAIR_UNCONSTRAINED_VLAN, PORT_PAIR_MATCHING_VLAN
    public var portPairVlan: InterconnectRemoteLocationConstraints.PortPairVlan? = nil

    /// Output only. [Output Only]
    ///
    /// [min-length, max-length]
    ///
    /// The minimum and maximum value (inclusive) for the IPv4 subnet
    /// length.
    ///
    ///  For example, an  interconnectRemoteLocation for Azure has {min: 30,
    /// max:
    /// 30} because Azure requires /30 subnets.
    ///
    /// This range specifies the values supported by both cloud providers.
    /// Interconnect currently supports /29 and /30 IPv4 subnet lengths. If a
    /// remote cloud has no constraint on IPv4 subnet length, the range would
    /// thus be {min: 29, max: 30}.
    public var subnetLengthRange: InterconnectRemoteLocationConstraintsSubnetLengthRange? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `InterconnectRemoteLocationConstraints`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InterconnectRemoteLocationConstraints().with { $0.portPairRemoteLocation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let portPairRemoteLocation = CodingKeys(stringValue: "portPairRemoteLocation")
      static let portPairVlan = CodingKeys(stringValue: "portPairVlan")
      static let subnetLengthRange = CodingKeys(stringValue: "subnetLengthRange")

      static let _knownKeys: Set<Swift.String> = [
        "portPairRemoteLocation",
        "portPairVlan",
        "subnetLengthRange",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.portPairRemoteLocation = try container.decodeIfPresent(
        InterconnectRemoteLocationConstraints.PortPairRemoteLocation.self,
        forKey: .portPairRemoteLocation)
      self.portPairVlan = try container.decodeIfPresent(
        InterconnectRemoteLocationConstraints.PortPairVlan.self, forKey: .portPairVlan)
      self.subnetLengthRange = try container.decodeIfPresent(
        InterconnectRemoteLocationConstraintsSubnetLengthRange.self, forKey: .subnetLengthRange)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.portPairRemoteLocation, forKey: .portPairRemoteLocation)
      try container.encodeIfPresent(self.portPairVlan, forKey: .portPairVlan)
      try container.encodeIfPresent(self.subnetLengthRange, forKey: .subnetLengthRange)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [portPairRemoteLocation][google.cloud.compute.v1.InterconnectRemoteLocationConstraints.portPairRemoteLocation] field.
    ///
    /// [google.cloud.compute.v1.InterconnectRemoteLocationConstraints.portPairRemoteLocation]: <doc:InterconnectRemoteLocationConstraints/PortPairRemoteLocation>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum PortPairRemoteLocation: Codable, Equatable, Sendable {
      /// If PORT_PAIR_MATCHING_REMOTE_LOCATION, the remote cloud provider
      /// allocates ports in pairs, and the user should choose the same remote
      /// location for both ports.
      case portPairMatchingRemoteLocation
      /// If PORT_PAIR_UNCONSTRAINED_REMOTE_LOCATION, a user may opt to provision
      /// a redundant pair of Cross-Cloud Interconnects using two different
      /// remote locations in the same city.
      case portPairUnconstrainedRemoteLocation
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .portPairMatchingRemoteLocation: return "PORT_PAIR_MATCHING_REMOTE_LOCATION"
        case .portPairUnconstrainedRemoteLocation: return "PORT_PAIR_UNCONSTRAINED_REMOTE_LOCATION"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PortPairRemoteLocation/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PORT_PAIR_MATCHING_REMOTE_LOCATION": self = .portPairMatchingRemoteLocation
        case "PORT_PAIR_UNCONSTRAINED_REMOTE_LOCATION": self = .portPairUnconstrainedRemoteLocation
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .portPairMatchingRemoteLocation:
          return try container.encode("PORT_PAIR_MATCHING_REMOTE_LOCATION")
        case .portPairUnconstrainedRemoteLocation:
          return try container.encode("PORT_PAIR_UNCONSTRAINED_REMOTE_LOCATION")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The enumerated type for the [portPairVlan][google.cloud.compute.v1.InterconnectRemoteLocationConstraints.portPairVlan] field.
    ///
    /// [google.cloud.compute.v1.InterconnectRemoteLocationConstraints.portPairVlan]: <doc:InterconnectRemoteLocationConstraints/PortPairVlan>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum PortPairVlan: Codable, Equatable, Sendable {
      /// If PORT_PAIR_MATCHING_VLAN, the Interconnect for this attachment is
      /// part of a pair of ports that should have matching VLAN allocations.
      /// This occurs with Cross-Cloud Interconnect to Azure remote locations.
      /// While GCP's API does not explicitly group pairs of ports, the UI uses
      /// this field to ensure matching VLAN ids when configuring a redundant
      /// VLAN pair.
      case portPairMatchingVlan
      /// PORT_PAIR_UNCONSTRAINED_VLAN means there is no constraint.
      case portPairUnconstrainedVlan
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .portPairMatchingVlan: return "PORT_PAIR_MATCHING_VLAN"
        case .portPairUnconstrainedVlan: return "PORT_PAIR_UNCONSTRAINED_VLAN"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PortPairVlan/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PORT_PAIR_MATCHING_VLAN": self = .portPairMatchingVlan
        case "PORT_PAIR_UNCONSTRAINED_VLAN": self = .portPairUnconstrainedVlan
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .portPairMatchingVlan: return try container.encode("PORT_PAIR_MATCHING_VLAN")
        case .portPairUnconstrainedVlan: return try container.encode("PORT_PAIR_UNCONSTRAINED_VLAN")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.InterconnectRemoteLocationConstraints"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
