// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if LicenseCodes
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  extension LicenseCodesClient {
    /// Synthetic request message for the [get()][google.cloud.compute.v1.licenseCodes.get] method.
    ///
    /// [google.cloud.compute.v1.licenseCodes.get]: <doc:LicenseCodesClient/`get`(request:options:)>
    public struct GetRequest: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Number corresponding to the License code resource to return.
      public var licenseCode: Swift.String = Swift.String()

      /// Project ID for this request.
      public var project: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `GetRequest`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GetRequest().with { $0.licenseCode = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let licenseCode = CodingKeys(stringValue: "licenseCode")
        static let project = CodingKeys(stringValue: "project")

        static let _knownKeys: Set<Swift.String> = [
          "licenseCode",
          "project",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .licenseCode) {
          self.licenseCode = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
          self.project = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.licenseCode, forKey: .licenseCode)
        try container.encode(self.project, forKey: .project)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.compute.v1.licenseCodes.getRequest"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Synthetic request message for the [getIamPolicy()][google.cloud.compute.v1.licenseCodes.getIamPolicy] method.
    ///
    /// [google.cloud.compute.v1.licenseCodes.getIamPolicy]: <doc:LicenseCodesClient/getIamPolicy(request:options:)>
    public struct GetIamPolicyRequest: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Requested IAM Policy version.
      public var optionsRequestedPolicyVersion: Swift.Int32? = nil

      /// Project ID for this request.
      public var project: Swift.String = Swift.String()

      /// Name or id of the resource for this request.
      public var resource: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `GetIamPolicyRequest`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GetIamPolicyRequest().with { $0.optionsRequestedPolicyVersion = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let optionsRequestedPolicyVersion = CodingKeys(
          stringValue: "optionsRequestedPolicyVersion")
        static let project = CodingKeys(stringValue: "project")
        static let resource = CodingKeys(stringValue: "resource")

        static let _knownKeys: Set<Swift.String> = [
          "optionsRequestedPolicyVersion",
          "project",
          "resource",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.optionsRequestedPolicyVersion = try container.decodeIfPresent(
          Swift.Int32.self, forKey: .optionsRequestedPolicyVersion)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
          self.project = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
          self.resource = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(
          self.optionsRequestedPolicyVersion, forKey: .optionsRequestedPolicyVersion)
        try container.encode(self.project, forKey: .project)
        try container.encode(self.resource, forKey: .resource)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.compute.v1.licenseCodes.getIamPolicyRequest"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Synthetic request message for the [setIamPolicy()][google.cloud.compute.v1.licenseCodes.setIamPolicy] method.
    ///
    /// [google.cloud.compute.v1.licenseCodes.setIamPolicy]: <doc:LicenseCodesClient/setIamPolicy(request:options:)>
    public struct SetIamPolicyRequest: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Project ID for this request.
      public var project: Swift.String = Swift.String()

      /// Name or id of the resource for this request.
      public var resource: Swift.String = Swift.String()

      /// Synthetic request body field for the [setIamPolicy()][google.cloud.compute.v1.licenseCodes.setIamPolicy] method.
      ///
      /// [google.cloud.compute.v1.licenseCodes.setIamPolicy]: <doc:LicenseCodesClient/setIamPolicy(request:options:)>
      public var body: GlobalSetPolicyRequest? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `SetIamPolicyRequest`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SetIamPolicyRequest().with { $0.project = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let project = CodingKeys(stringValue: "project")
        static let resource = CodingKeys(stringValue: "resource")
        static let body = CodingKeys(stringValue: "body")

        static let _knownKeys: Set<Swift.String> = [
          "project",
          "resource",
          "body",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
          self.project = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
          self.resource = value
        }
        self.body = try container.decodeIfPresent(GlobalSetPolicyRequest.self, forKey: .body)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.project, forKey: .project)
        try container.encode(self.resource, forKey: .resource)
        try container.encodeIfPresent(self.body, forKey: .body)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.compute.v1.licenseCodes.setIamPolicyRequest"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Synthetic request message for the [testIamPermissions()][google.cloud.compute.v1.licenseCodes.testIamPermissions] method.
    ///
    /// [google.cloud.compute.v1.licenseCodes.testIamPermissions]: <doc:LicenseCodesClient/testIamPermissions(request:options:)>
    public struct TestIamPermissionsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Project ID for this request.
      public var project: Swift.String = Swift.String()

      /// Name or id of the resource for this request.
      public var resource: Swift.String = Swift.String()

      /// Synthetic request body field for the [testIamPermissions()][google.cloud.compute.v1.licenseCodes.testIamPermissions] method.
      ///
      /// [google.cloud.compute.v1.licenseCodes.testIamPermissions]: <doc:LicenseCodesClient/testIamPermissions(request:options:)>
      public var body: TestPermissionsRequest? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `TestIamPermissionsRequest`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TestIamPermissionsRequest().with { $0.project = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let project = CodingKeys(stringValue: "project")
        static let resource = CodingKeys(stringValue: "resource")
        static let body = CodingKeys(stringValue: "body")

        static let _knownKeys: Set<Swift.String> = [
          "project",
          "resource",
          "body",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .project) {
          self.project = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
          self.resource = value
        }
        self.body = try container.decodeIfPresent(TestPermissionsRequest.self, forKey: .body)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.project, forKey: .project)
        try container.encode(self.resource, forKey: .resource)
        try container.encodeIfPresent(self.body, forKey: .body)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.compute.v1.licenseCodes.testIamPermissionsRequest"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }
  }
#endif
