// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Instances || RegionInstances
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Configuration for location policy among multiple possible locations
  /// (e.g. preferences for zone selection among zones in a single region).
  public struct LocationPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Location configurations mapped by location name.
    /// Currently only zone names are supported and must be represented as valid
    /// internal URLs, such as zones/us-central1-a.
    /// The bulkInsert operation doesn't create instances in an AI zone, even if
    /// an AI zone is available in the specified region. For example, if you set a
    /// DENY preference for us-central1-a, Compute Engine will consider
    /// us-central1-b and us-central1-c for instance creation, but not
    /// us-central1-ai1a. Also, you can't use the locations[] configuration to
    /// allow instance creation in an AI zone. To include an AI zone in bulkInsert
    /// operations, use the locationPolicy.zones[] field.
    public var locations: [Swift.String: LocationPolicyLocation] = [:]

    /// Strategy for distributing VMs across zones in a region.
    public var targetShape: LocationPolicy.TargetShape? = nil

    /// The bulkInsert operation applies any preferences set in the locations
    /// field to the specific zones listed in the zones field if the same zones
    /// are specified in both fields.
    public var zones: [LocationPolicyZoneConfiguration] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LocationPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LocationPolicy().with { $0.locations = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let locations = CodingKeys(stringValue: "locations")
      static let targetShape = CodingKeys(stringValue: "targetShape")
      static let zones = CodingKeys(stringValue: "zones")

      static let _knownKeys: Set<Swift.String> = [
        "locations",
        "targetShape",
        "zones",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Swift.String: LocationPolicyLocation].self, forKey: .locations)
      {
        self.locations = value
      }
      self.targetShape = try container.decodeIfPresent(
        LocationPolicy.TargetShape.self, forKey: .targetShape)
      if let value = try container.decodeIfPresent(
        [LocationPolicyZoneConfiguration].self, forKey: .zones)
      {
        self.zones = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.locations, forKey: .locations)
      try container.encodeIfPresent(self.targetShape, forKey: .targetShape)
      try container.encode(self.zones, forKey: .zones)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [targetShape][google.cloud.compute.v1.LocationPolicy.targetShape] field.
    ///
    /// [google.cloud.compute.v1.LocationPolicy.targetShape]: <doc:LocationPolicy/TargetShape>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum TargetShape: Codable, Equatable, Sendable {
      /// GCE picks zones for creating VM instances to fulfill the requested
      /// number of VMs within present resource constraints and to maximize
      /// utilization of unused zonal reservations. Recommended for batch workloads
      /// that do not require high availability.
      case any
      /// GCE always selects a single zone for all the VMs, optimizing for resource
      /// quotas, available reservations and general capacity. Recommended for
      /// batch workloads that cannot tollerate distribution over multiple zones.
      /// This the default shape in Bulk Insert and Capacity Advisor APIs.
      case anySingleZone
      /// GCE prioritizes acquisition of resources, scheduling VMs in zones
      /// where resources are available while distributing VMs as evenly as
      /// possible across allowed zones to minimize the impact of zonal failure.
      /// Recommended for highly available serving workloads.
      case balanced
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .any: return "ANY"
        case .anySingleZone: return "ANY_SINGLE_ZONE"
        case .balanced: return "BALANCED"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TargetShape/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ANY": self = .any
        case "ANY_SINGLE_ZONE": self = .anySingleZone
        case "BALANCED": self = .balanced
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .any: return try container.encode("ANY")
        case .anySingleZone: return try container.encode("ANY_SINGLE_ZONE")
        case .balanced: return try container.encode("BALANCED")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.LocationPolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
