// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if MachineImages
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) import GoogleGax

  extension Clients {
    final class MachineImagesRetry: MachineImagesStub {
      let inner: any MachineImagesStub
      let options: GoogleGax.ClientOptions

      public init(_ inner: any MachineImagesStub, options: GoogleGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func delete(
        request: MachineImagesClient.DeleteRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: MachineImagesClient.DeleteRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func `get`(
        request: MachineImagesClient.GetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.MachineImage {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: MachineImagesClient.GetRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.MachineImage
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func getIamPolicy(
        request: MachineImagesClient.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: MachineImagesClient.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Policy
            in
            return try await self.inner.getIamPolicy(request: r, options: o)
          })
      }

      public func insert(
        request: MachineImagesClient.InsertRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: MachineImagesClient.InsertRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: MachineImagesClient.ListRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.MachineImageList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: MachineImagesClient.ListRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.MachineImageList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func setIamPolicy(
        request: MachineImagesClient.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: MachineImagesClient.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Policy
            in
            return try await self.inner.setIamPolicy(request: r, options: o)
          })
      }

      public func setLabels(
        request: MachineImagesClient.SetLabelsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: MachineImagesClient.SetLabelsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.setLabels(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: MachineImagesClient.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: MachineImagesClient.TestIamPermissionsRequest, o: GoogleGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.TestPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }

      public func getOperation(
        request: GlobalOperationsClient.GetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GlobalOperationsClient.GetRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }
    }
  }
#endif
