// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if NetworkAttachments
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Service for the `networkAttachments` resource.
  ///
  /// @Snippet(path: "networkAttachmentsQuickstart")
  public final class NetworkAttachmentsClient: Clients.NetworkAttachmentsProtocol, Sendable {
    let inner: any Clients.NetworkAttachmentsStub
    let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
    let pollingBackoffPolicy: GoogleGax.BackoffPolicy

    /// Creates a new `NetworkAttachmentsClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.NetworkAttachmentsStub = try Clients.NetworkAttachmentsTransport(
        options)
      inner = Clients.NetworkAttachmentsRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.NetworkAttachmentsLogging(inner, logger: logger)
      }
      self.inner = inner
      self.pollingErrorPolicy = options.pollingErrorPolicy
      self.pollingBackoffPolicy = options.pollingBackoffPolicy
    }

    /// Retrieves the list of all NetworkAttachment resources,
    /// regional and global, available to the specified project.
    ///
    /// To prevent failure, Google recommends that you set the
    /// `returnPartialSuccess` parameter to `true`.
    ///
    /// @Snippet(path: "networkAttachments_aggregatedList")
    public func aggregatedList(
      request: NetworkAttachmentsClient.AggregatedListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.NetworkAttachmentAggregatedList {
      try await self.inner.aggregatedList(request: request, options: options)
    }

    /// Deletes the specified NetworkAttachment in the given scope
    ///
    /// @Snippet(path: "networkAttachments_delete")
    public func delete(
      request: NetworkAttachmentsClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.delete(request: request, options: options)
    }

    /// Deletes the specified NetworkAttachment in the given scope
    ///
    /// @Snippet(path: "networkAttachments_delete")
    public func deletePollingUntilDone(
      request: NetworkAttachmentsClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.delete(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
            $0.region = request.region
          }, options: options)
        return try extractStatus(op)
      }
      return GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
    }

    /// Returns the specified NetworkAttachment resource in the given scope.
    ///
    /// @Snippet(path: "networkAttachments_get")
    public func `get`(
      request: NetworkAttachmentsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.NetworkAttachment {
      try await self.inner.`get`(request: request, options: options)
    }

    /// Gets the access control policy for a resource. May be empty if no such
    /// policy or resource exists.
    ///
    /// @Snippet(path: "networkAttachments_getIamPolicy")
    public func getIamPolicy(
      request: NetworkAttachmentsClient.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Policy {
      try await self.inner.getIamPolicy(request: request, options: options)
    }

    /// Creates a NetworkAttachment in the specified project in the given scope
    /// using the parameters that are included in the request.
    ///
    /// @Snippet(path: "networkAttachments_insert")
    public func insert(
      request: NetworkAttachmentsClient.InsertRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.insert(request: request, options: options)
    }

    /// Creates a NetworkAttachment in the specified project in the given scope
    /// using the parameters that are included in the request.
    ///
    /// @Snippet(path: "networkAttachments_insert")
    public func insertPollingUntilDone(
      request: NetworkAttachmentsClient.InsertRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.insert(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
            $0.region = request.region
          }, options: options)
        return try extractStatus(op)
      }
      return GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
    }

    /// Lists the NetworkAttachments for a project in the given scope.
    ///
    /// @Snippet(path: "networkAttachments_list")
    public func list(
      request: NetworkAttachmentsClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.NetworkAttachmentList {
      try await self.inner.list(request: request, options: options)
    }

    /// Patches the specified NetworkAttachment resource with the data included in
    /// the request. This method supports PATCH
    /// semantics and usesJSON merge
    /// patch format and processing rules.
    ///
    /// @Snippet(path: "networkAttachments_patch")
    public func patch(
      request: NetworkAttachmentsClient.PatchRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.patch(request: request, options: options)
    }

    /// Patches the specified NetworkAttachment resource with the data included in
    /// the request. This method supports PATCH
    /// semantics and usesJSON merge
    /// patch format and processing rules.
    ///
    /// @Snippet(path: "networkAttachments_patch")
    public func patchPollingUntilDone(
      request: NetworkAttachmentsClient.PatchRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.patch(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
            $0.region = request.region
          }, options: options)
        return try extractStatus(op)
      }
      return GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
    }

    /// Sets the access control policy on the specified resource.
    /// Replaces any existing policy.
    ///
    /// @Snippet(path: "networkAttachments_setIamPolicy")
    public func setIamPolicy(
      request: NetworkAttachmentsClient.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Policy {
      try await self.inner.setIamPolicy(request: request, options: options)
    }

    /// Returns permissions that a caller has on the specified resource.
    ///
    /// @Snippet(path: "networkAttachments_testIamPermissions")
    public func testIamPermissions(
      request: NetworkAttachmentsClient.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// Retrieves the specified region-specific Operations resource.
    ///
    /// @Snippet(path: "networkAttachments_getOperation")
    func getOperation(
      request: RegionOperationsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `NetworkAttachmentsClient`.
    ///
    /// To mock `NetworkAttachmentsClient` change your functions to receive
    /// `some NetworkAttachmentsProtocol` or `any NetworkAttachmentsProtocol`
    /// and pass a mock implementation in your tests.
    public protocol NetworkAttachmentsProtocol: Sendable {
      /// See `NetworkAttachmentsClient.aggregatedList`.
      func aggregatedList(
        request: NetworkAttachmentsClient.AggregatedListRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NetworkAttachmentAggregatedList

      /// See `NetworkAttachmentsClient.delete`.
      func delete(
        request: NetworkAttachmentsClient.DeleteRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `NetworkAttachmentsClient.`get``.
      func `get`(
        request: NetworkAttachmentsClient.GetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NetworkAttachment

      /// See `NetworkAttachmentsClient.getIamPolicy`.
      func getIamPolicy(
        request: NetworkAttachmentsClient.GetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy

      /// See `NetworkAttachmentsClient.insert`.
      func insert(
        request: NetworkAttachmentsClient.InsertRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `NetworkAttachmentsClient.list`.
      func list(
        request: NetworkAttachmentsClient.ListRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NetworkAttachmentList

      /// See `NetworkAttachmentsClient.patch`.
      func patch(
        request: NetworkAttachmentsClient.PatchRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `NetworkAttachmentsClient.setIamPolicy`.
      func setIamPolicy(
        request: NetworkAttachmentsClient.SetIamPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy

      /// See `NetworkAttachmentsClient.testIamPermissions`.
      func testIamPermissions(
        request: NetworkAttachmentsClient.TestIamPermissionsRequest,
        options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse
    }
  }

  // Default implementations
  extension Clients.NetworkAttachmentsProtocol {
    public func aggregatedList(request: NetworkAttachmentsClient.AggregatedListRequest) async throws
      -> GoogleCloudComputeV1.NetworkAttachmentAggregatedList
    {
      try await self.aggregatedList(request: request, options: .init())
    }

    public func aggregatedList(
      request: NetworkAttachmentsClient.AggregatedListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.NetworkAttachmentAggregatedList {
      throw GoogleGax.RequestError.unimplemented
    }

    public func aggregatedListByItems(
      request: NetworkAttachmentsClient.AggregatedListRequest
    ) -> any AsyncSequence<(Swift.String, NetworkAttachmentsScopedList), Swift.Error> & Sendable {
      self.aggregatedListByItems(request: request, options: .init())
    }

    /// Retrieves the list of all NetworkAttachment resources,
    /// regional and global, available to the specified project.
    ///
    /// To prevent failure, Google recommends that you set the
    /// `returnPartialSuccess` parameter to `true`.
    ///
    /// @Snippet(path: "networkAttachments_aggregatedList")
    public func aggregatedListByItems(
      request: NetworkAttachmentsClient.AggregatedListRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<(Swift.String, NetworkAttachmentsScopedList), Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudComputeV1.NetworkAttachmentAggregatedList in
        var request = request
        request.pageToken = token
        return try await self.aggregatedList(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func aggregatedListByItems(
      project: Swift.String,
    ) -> any AsyncSequence<(Swift.String, NetworkAttachmentsScopedList), Swift.Error> & Sendable {
      let request = NetworkAttachmentsClient.AggregatedListRequest().with {
        $0.project = project
      }
      return self.aggregatedListByItems(request: request)
    }

    public func delete(request: NetworkAttachmentsClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: NetworkAttachmentsClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deletePollingUntilDone(
      request: NetworkAttachmentsClient.DeleteRequest
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      try await self.deletePollingUntilDone(request: request, options: .init())
    }

    public func deletePollingUntilDone(
      request: NetworkAttachmentsClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        throw GoogleGax.RequestError.unimplemented
      }
      return GoogleGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func deletePollingUntilDone(
      project: Swift.String,
      region: Swift.String,
      networkAttachment: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let request = NetworkAttachmentsClient.DeleteRequest().with {
        $0.project = project
        $0.region = region
        $0.networkAttachment = networkAttachment
      }
      return try await self.deletePollingUntilDone(request: request)
    }

    public func `get`(request: NetworkAttachmentsClient.GetRequest) async throws
      -> GoogleCloudComputeV1.NetworkAttachment
    {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: NetworkAttachmentsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.NetworkAttachment {
      throw GoogleGax.RequestError.unimplemented
    }

    public func `get`(
      project: Swift.String,
      region: Swift.String,
      networkAttachment: Swift.String,
    ) async throws -> GoogleCloudComputeV1.NetworkAttachment {
      let request = NetworkAttachmentsClient.GetRequest().with {
        $0.project = project
        $0.region = region
        $0.networkAttachment = networkAttachment
      }
      return try await self.`get`(request: request)
    }

    public func getIamPolicy(request: NetworkAttachmentsClient.GetIamPolicyRequest) async throws
      -> GoogleCloudComputeV1.Policy
    {
      try await self.getIamPolicy(request: request, options: .init())
    }

    public func getIamPolicy(
      request: NetworkAttachmentsClient.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Policy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getIamPolicy(
      project: Swift.String,
      region: Swift.String,
      resource: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Policy {
      let request = NetworkAttachmentsClient.GetIamPolicyRequest().with {
        $0.project = project
        $0.region = region
        $0.resource = resource
      }
      return try await self.getIamPolicy(request: request)
    }

    public func insert(request: NetworkAttachmentsClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.insert(request: request, options: .init())
    }

    public func insert(
      request: NetworkAttachmentsClient.InsertRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func insertPollingUntilDone(
      request: NetworkAttachmentsClient.InsertRequest
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      try await self.insertPollingUntilDone(request: request, options: .init())
    }

    public func insertPollingUntilDone(
      request: NetworkAttachmentsClient.InsertRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        throw GoogleGax.RequestError.unimplemented
      }
      return GoogleGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func insertPollingUntilDone(
      project: Swift.String,
      region: Swift.String,
      body: NetworkAttachment?,
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let request = NetworkAttachmentsClient.InsertRequest().with {
        $0.project = project
        $0.region = region
        $0.body = body
      }
      return try await self.insertPollingUntilDone(request: request)
    }

    public func list(request: NetworkAttachmentsClient.ListRequest) async throws
      -> GoogleCloudComputeV1.NetworkAttachmentList
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: NetworkAttachmentsClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.NetworkAttachmentList {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listByItems(
      request: NetworkAttachmentsClient.ListRequest
    ) -> any AsyncSequence<NetworkAttachment, Swift.Error> & Sendable {
      self.listByItems(request: request, options: .init())
    }

    /// Lists the NetworkAttachments for a project in the given scope.
    ///
    /// @Snippet(path: "networkAttachments_list")
    public func listByItems(
      request: NetworkAttachmentsClient.ListRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<NetworkAttachment, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudComputeV1.NetworkAttachmentList
        in
        var request = request
        request.pageToken = token
        return try await self.list(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listByItems(
      project: Swift.String,
      region: Swift.String,
    ) -> any AsyncSequence<NetworkAttachment, Swift.Error> & Sendable {
      let request = NetworkAttachmentsClient.ListRequest().with {
        $0.project = project
        $0.region = region
      }
      return self.listByItems(request: request)
    }

    public func patch(request: NetworkAttachmentsClient.PatchRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.patch(request: request, options: .init())
    }

    public func patch(
      request: NetworkAttachmentsClient.PatchRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func patchPollingUntilDone(
      request: NetworkAttachmentsClient.PatchRequest
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      try await self.patchPollingUntilDone(request: request, options: .init())
    }

    public func patchPollingUntilDone(
      request: NetworkAttachmentsClient.PatchRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        throw GoogleGax.RequestError.unimplemented
      }
      return GoogleGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func patchPollingUntilDone(
      project: Swift.String,
      region: Swift.String,
      networkAttachment: Swift.String,
      body: NetworkAttachment?,
    ) async throws -> any GoogleGax.PollableOperation<GoogleCloudComputeV1.Operation> {
      let request = NetworkAttachmentsClient.PatchRequest().with {
        $0.project = project
        $0.region = region
        $0.networkAttachment = networkAttachment
        $0.body = body
      }
      return try await self.patchPollingUntilDone(request: request)
    }

    public func setIamPolicy(request: NetworkAttachmentsClient.SetIamPolicyRequest) async throws
      -> GoogleCloudComputeV1.Policy
    {
      try await self.setIamPolicy(request: request, options: .init())
    }

    public func setIamPolicy(
      request: NetworkAttachmentsClient.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Policy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setIamPolicy(
      project: Swift.String,
      region: Swift.String,
      resource: Swift.String,
      body: RegionSetPolicyRequest?,
    ) async throws -> GoogleCloudComputeV1.Policy {
      let request = NetworkAttachmentsClient.SetIamPolicyRequest().with {
        $0.project = project
        $0.region = region
        $0.resource = resource
        $0.body = body
      }
      return try await self.setIamPolicy(request: request)
    }

    public func testIamPermissions(request: NetworkAttachmentsClient.TestIamPermissionsRequest)
      async throws -> GoogleCloudComputeV1.TestPermissionsResponse
    {
      try await self.testIamPermissions(request: request, options: .init())
    }

    public func testIamPermissions(
      request: NetworkAttachmentsClient.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func testIamPermissions(
      project: Swift.String,
      region: Swift.String,
      resource: Swift.String,
      body: TestPermissionsRequest?,
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      let request = NetworkAttachmentsClient.TestIamPermissionsRequest().with {
        $0.project = project
        $0.region = region
        $0.resource = resource
        $0.body = body
      }
      return try await self.testIamPermissions(request: request)
    }

    public func getOperation(request: RegionOperationsClient.GetRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: RegionOperationsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'NetworkAttachments' trait in Package.swift to use this client."
  )
  public final class NetworkAttachmentsClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'NetworkAttachments' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
