// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if NodeGroups
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  public struct NodeGroupNode: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Accelerators for this node.
    public var accelerators: [AcceleratorConfig] = []

    /// Output only. Node resources that are reserved by all instances.
    public var consumedResources: InstanceConsumptionInfo? = nil

    /// CPU overcommit.
    public var cpuOvercommitType: NodeGroupNode.CpuOvercommitType? = nil

    /// Local disk configurations.
    public var disks: [LocalDisk] = []

    /// Output only. Instance data that shows consumed resources on the node.
    public var instanceConsumptionData: [InstanceConsumptionData] = []

    /// Instances scheduled on this node.
    public var instances: [Swift.String] = []

    /// The name of the node.
    public var name: Swift.String? = nil

    /// The type of this node.
    public var nodeType: Swift.String? = nil

    /// Output only. [Output Only] Reserved for future use.
    public var satisfiesPzs: Swift.Bool? = nil

    /// Binding properties for the physical server.
    public var serverBinding: ServerBinding? = nil

    /// Server ID associated with this node.
    public var serverId: Swift.String? = nil

    public var status: NodeGroupNode.Status? = nil

    /// Output only. Total amount of available resources on the node.
    public var totalResources: InstanceConsumptionInfo? = nil

    /// Output only. [Output Only] The information about an upcoming maintenance event.
    public var upcomingMaintenance: UpcomingMaintenance? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NodeGroupNode`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NodeGroupNode().with { $0.accelerators = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let accelerators = CodingKeys(stringValue: "accelerators")
      static let consumedResources = CodingKeys(stringValue: "consumedResources")
      static let cpuOvercommitType = CodingKeys(stringValue: "cpuOvercommitType")
      static let disks = CodingKeys(stringValue: "disks")
      static let instanceConsumptionData = CodingKeys(stringValue: "instanceConsumptionData")
      static let instances = CodingKeys(stringValue: "instances")
      static let name = CodingKeys(stringValue: "name")
      static let nodeType = CodingKeys(stringValue: "nodeType")
      static let satisfiesPzs = CodingKeys(stringValue: "satisfiesPzs")
      static let serverBinding = CodingKeys(stringValue: "serverBinding")
      static let serverId = CodingKeys(stringValue: "serverId")
      static let status = CodingKeys(stringValue: "status")
      static let totalResources = CodingKeys(stringValue: "totalResources")
      static let upcomingMaintenance = CodingKeys(stringValue: "upcomingMaintenance")

      static let _knownKeys: Set<Swift.String> = [
        "accelerators",
        "consumedResources",
        "cpuOvercommitType",
        "disks",
        "instanceConsumptionData",
        "instances",
        "name",
        "nodeType",
        "satisfiesPzs",
        "serverBinding",
        "serverId",
        "status",
        "totalResources",
        "upcomingMaintenance",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([AcceleratorConfig].self, forKey: .accelerators)
      {
        self.accelerators = value
      }
      self.consumedResources = try container.decodeIfPresent(
        InstanceConsumptionInfo.self, forKey: .consumedResources)
      self.cpuOvercommitType = try container.decodeIfPresent(
        NodeGroupNode.CpuOvercommitType.self, forKey: .cpuOvercommitType)
      if let value = try container.decodeIfPresent([LocalDisk].self, forKey: .disks) {
        self.disks = value
      }
      if let value = try container.decodeIfPresent(
        [InstanceConsumptionData].self, forKey: .instanceConsumptionData)
      {
        self.instanceConsumptionData = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .instances) {
        self.instances = value
      }
      self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
      self.nodeType = try container.decodeIfPresent(Swift.String.self, forKey: .nodeType)
      self.satisfiesPzs = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs)
      self.serverBinding = try container.decodeIfPresent(ServerBinding.self, forKey: .serverBinding)
      self.serverId = try container.decodeIfPresent(Swift.String.self, forKey: .serverId)
      self.status = try container.decodeIfPresent(NodeGroupNode.Status.self, forKey: .status)
      self.totalResources = try container.decodeIfPresent(
        InstanceConsumptionInfo.self, forKey: .totalResources)
      self.upcomingMaintenance = try container.decodeIfPresent(
        UpcomingMaintenance.self, forKey: .upcomingMaintenance)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.accelerators, forKey: .accelerators)
      try container.encodeIfPresent(self.consumedResources, forKey: .consumedResources)
      try container.encodeIfPresent(self.cpuOvercommitType, forKey: .cpuOvercommitType)
      try container.encode(self.disks, forKey: .disks)
      try container.encode(self.instanceConsumptionData, forKey: .instanceConsumptionData)
      try container.encode(self.instances, forKey: .instances)
      try container.encodeIfPresent(self.name, forKey: .name)
      try container.encodeIfPresent(self.nodeType, forKey: .nodeType)
      try container.encodeIfPresent(self.satisfiesPzs, forKey: .satisfiesPzs)
      try container.encodeIfPresent(self.serverBinding, forKey: .serverBinding)
      try container.encodeIfPresent(self.serverId, forKey: .serverId)
      try container.encodeIfPresent(self.status, forKey: .status)
      try container.encodeIfPresent(self.totalResources, forKey: .totalResources)
      try container.encodeIfPresent(self.upcomingMaintenance, forKey: .upcomingMaintenance)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [cpuOvercommitType][google.cloud.compute.v1.NodeGroupNode.cpuOvercommitType] field.
    ///
    /// [google.cloud.compute.v1.NodeGroupNode.cpuOvercommitType]: <doc:NodeGroupNode/CpuOvercommitType>
    public enum CpuOvercommitType: Codable, Equatable, Sendable {
      case unspecified
      case enabled
      case `none`
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .enabled: return 1
        case .`none`: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CPU_OVERCOMMIT_TYPE_UNSPECIFIED"
        case .enabled: return "ENABLED"
        case .`none`: return "NONE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CpuOvercommitType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CPU_OVERCOMMIT_TYPE_UNSPECIFIED": self = .unspecified
        case "ENABLED": self = .enabled
        case "NONE": self = .`none`
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CpuOvercommitType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .enabled
        case 2: self = .`none`
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("CPU_OVERCOMMIT_TYPE_UNSPECIFIED")
        case .enabled: return try container.encode("ENABLED")
        case .`none`: return try container.encode("NONE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The enumerated type for the [status][google.cloud.compute.v1.NodeGroupNode.status] field.
    ///
    /// [google.cloud.compute.v1.NodeGroupNode.status]: <doc:NodeGroupNode/Status>
    public enum Status: Codable, Equatable, Sendable {
      case creating
      case deleting
      case invalid
      case ready
      case repairing
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .creating
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .creating: return 0
        case .deleting: return 1
        case .invalid: return 2
        case .ready: return 3
        case .repairing: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .creating: return "CREATING"
        case .deleting: return "DELETING"
        case .invalid: return "INVALID"
        case .ready: return "READY"
        case .repairing: return "REPAIRING"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Status/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CREATING": self = .creating
        case "DELETING": self = .deleting
        case "INVALID": self = .invalid
        case "READY": self = .ready
        case "REPAIRING": self = .repairing
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Status/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .creating
        case 1: self = .deleting
        case 2: self = .invalid
        case 3: self = .ready
        case 4: self = .repairing
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .creating: return try container.encode("CREATING")
        case .deleting: return try container.encode("DELETING")
        case .invalid: return try container.encode("INVALID")
        case .ready: return try container.encode("READY")
        case .repairing: return try container.encode("REPAIRING")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.NodeGroupNode"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
