// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if NodeTypes
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleCloudGax
  import struct Logging.Logger

  extension Clients {
    final class NodeTypesLogging: NodeTypesStub {
      let inner: any NodeTypesStub
      let logger: Logger

      public init(_ inner: any NodeTypesStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudComputeV1"
        logger[metadataKey: "gcp.client.service"] = "compute"
        logger[metadataKey: "gcp.experimental.swift.client"] = "NodeTypes"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        name: Swift.String,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func aggregatedList(
        request: NodeTypesClient.AggregatedListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NodeTypeAggregatedList {
        try await self._intercept(
          request: request,
          options: options,
          name: "aggregatedList",
          action: {
            (r: NodeTypesClient.AggregatedListRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.NodeTypeAggregatedList
            in
            return try await self.inner.aggregatedList(request: r, options: o)
          })
      }

      public func `get`(
        request: NodeTypesClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NodeType {
        try await self._intercept(
          request: request,
          options: options,
          name: "`get`",
          action: {
            (r: NodeTypesClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.NodeType
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func list(
        request: NodeTypesClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NodeTypeList {
        try await self._intercept(
          request: request,
          options: options,
          name: "list",
          action: {
            (r: NodeTypesClient.ListRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.NodeTypeList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }
    }
  }
#endif
