// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ProjectViews
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Service for the `projectViews` resource.
  ///
  /// @Snippet(path: "projectViewsQuickstart")
  public final class ProjectViewsClient: Clients.ProjectViewsProtocol, Sendable {
    let inner: any Clients.ProjectViewsStub

    /// Creates a new `ProjectViewsClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.ProjectViewsStub = try Clients.ProjectViewsTransport(options)
      inner = Clients.ProjectViewsRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.ProjectViewsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Returns the specified global ProjectViews resource, with a regional
    /// context.
    /// This regional API endpoint reads resource metadata from regional
    /// read-only replicas. Because changes are copied to these regional replicas
    /// asynchronously, for real-time resource reads or any write operations
    /// (creating, updating, or deleting resources), use the global
    /// [projects.get](https://cloud.google.com/compute/docs/reference/rest/v1/projects/get)
    /// endpoint.
    ///
    /// @Snippet(path: "projectViews_get")
    public func `get`(
      request: ProjectViewsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.ProjectView {
      try await self.inner.`get`(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `ProjectViewsClient`.
    ///
    /// To mock `ProjectViewsClient` change your functions to receive
    /// `some ProjectViewsProtocol` or `any ProjectViewsProtocol`
    /// and pass a mock implementation in your tests.
    public protocol ProjectViewsProtocol: Sendable {
      /// See `ProjectViewsClient.`get``.
      func `get`(
        request: ProjectViewsClient.GetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.ProjectView
    }
  }

  // Default implementations
  extension Clients.ProjectViewsProtocol {
    public func `get`(request: ProjectViewsClient.GetRequest) async throws
      -> GoogleCloudComputeV1.ProjectView
    {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: ProjectViewsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.ProjectView {
      throw GoogleGax.RequestError.unimplemented
    }

    public func `get`(
      project: Swift.String,
      region: Swift.String,
    ) async throws -> GoogleCloudComputeV1.ProjectView {
      let request = ProjectViewsClient.GetRequest().with {
        $0.project = project
        $0.region = region
      }
      return try await self.`get`(request: request)
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable, message: "Enable the 'ProjectViews' trait in Package.swift to use this client."
  )
  public final class ProjectViewsClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'ProjectViews' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
