// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if RegionNotificationEndpoints
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  @_spi(GoogleCloudInternal) import GoogleCloudGax

  extension Clients {
    final class RegionNotificationEndpointsRetry: RegionNotificationEndpointsStub {
      let inner: any RegionNotificationEndpointsStub
      let options: GoogleCloudGax.ClientOptions

      public init(
        _ inner: any RegionNotificationEndpointsStub, options: GoogleCloudGax.ClientOptions
      ) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func aggregatedList(
        request: RegionNotificationEndpointsClient.AggregatedListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NotificationEndpointAggregatedList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (
              r: RegionNotificationEndpointsClient.AggregatedListRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.NotificationEndpointAggregatedList
            in
            return try await self.inner.aggregatedList(request: r, options: o)
          })
      }

      public func delete(
        request: RegionNotificationEndpointsClient.DeleteRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: RegionNotificationEndpointsClient.DeleteRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func `get`(
        request: RegionNotificationEndpointsClient.GetRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NotificationEndpoint {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: RegionNotificationEndpointsClient.GetRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.NotificationEndpoint
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func insert(
        request: RegionNotificationEndpointsClient.InsertRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: RegionNotificationEndpointsClient.InsertRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: RegionNotificationEndpointsClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.NotificationEndpointList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: RegionNotificationEndpointsClient.ListRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.NotificationEndpointList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: RegionNotificationEndpointsClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (
              r: RegionNotificationEndpointsClient.TestIamPermissionsRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }

      public func getOperation(
        request: RegionOperationsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: RegionOperationsClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }
    }
  }
#endif
