// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if RegionInstanceGroups
  public import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  public struct RegionInstanceGroupsSetNamedPortsRequest: Codable, Equatable, GoogleWKT
      ._AnyPackable,
    Sendable
  {
    /// The fingerprint of the named ports information for this instance group.
    /// Use this optional property to prevent conflicts when multiple users change
    /// the named ports settings concurrently. Obtain the fingerprint with theinstanceGroups.get
    /// method. Then, include the fingerprint in your request to ensure that you
    /// do not overwrite changes that were applied from another
    /// concurrent request.
    public var fingerprint: Foundation.Data? = nil

    /// The list of named ports to set for this instance group.
    public var namedPorts: [NamedPort] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RegionInstanceGroupsSetNamedPortsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RegionInstanceGroupsSetNamedPortsRequest().with { $0.fingerprint = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let fingerprint = CodingKeys(stringValue: "fingerprint")
      static let namedPorts = CodingKeys(stringValue: "namedPorts")

      static let _knownKeys: Set<Swift.String> = [
        "fingerprint",
        "namedPorts",
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let s = try container.decodeIfPresent(Swift.String.self, forKey: .fingerprint) {
        guard let v = GoogleWKT._DiscoveryBase64.decode(s) else {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath, debugDescription: "Expected url-safe encoded value")
          )
        }
        self.fingerprint = v
      }
      if let value = try container.decodeIfPresent([NamedPort].self, forKey: .namedPorts) {
        self.namedPorts = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      if let v = fingerprint {
        try container.encode(
          GoogleWKT._DiscoveryBase64.encode(v), forKey: .fingerprint
        )
      }
      try container.encode(self.namedPorts, forKey: .namedPorts)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The type URL for `RegionInstanceGroupsSetNamedPortsRequest`: `"type.googleapis.com/google.cloud.compute.v1.RegionInstanceGroupsSetNamedPortsRequest"`.
    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.RegionInstanceGroupsSetNamedPortsRequest"
    }

    /// Initialize an instance of `RegionInstanceGroupsSetNamedPortsRequest` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.compute.v1.RegionInstanceGroupsSetNamedPortsRequest"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `RegionInstanceGroupsSetNamedPortsRequest` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
