// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if RegionCompositeHealthChecks
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service for the `regionCompositeHealthChecks` resource.
  ///
  /// @Snippet(path: "regionCompositeHealthChecksQuickstart")
  public protocol RegionCompositeHealthChecks {
    /// Retrieves the list of all CompositeHealthCheck resources (all
    /// regional) available to the specified project.
    ///
    /// To prevent failure, it is recommended that you set the
    /// `returnPartialSuccess` parameter to `true`.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_aggregatedList")
    func aggregatedList(request: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest)
      async throws -> GoogleCloudComputeV1.CompositeHealthCheckAggregatedList

    /// Retrieves the list of all CompositeHealthCheck resources (all
    /// regional) available to the specified project.
    ///
    /// To prevent failure, it is recommended that you set the
    /// `returnPartialSuccess` parameter to `true`.
    func aggregatedList(
      byItem: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest
    ) throws -> any AsyncSequence<(Swift.String, CompositeHealthChecksScopedList), Swift.Error>

    /// Retrieves the list of all CompositeHealthCheck resources (all
    /// regional) available to the specified project.
    ///
    /// To prevent failure, it is recommended that you set the
    /// `returnPartialSuccess` parameter to `true`.
    func aggregatedList(
      project: Swift.String,
    ) throws -> any AsyncSequence<(Swift.String, CompositeHealthChecksScopedList), Swift.Error>

    /// Deletes the specified CompositeHealthCheck in the given region
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_delete")
    func delete(request: Clients.RegionCompositeHealthChecksClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Deletes the specified CompositeHealthCheck in the given region
    func delete(
      project: Swift.String,
      region: Swift.String,
      compositeHealthCheck: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns the specified CompositeHealthCheck resource in the given region.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_get")
    func `get`(request: Clients.RegionCompositeHealthChecksClient.GetRequest) async throws
      -> GoogleCloudComputeV1.CompositeHealthCheck

    /// Returns the specified CompositeHealthCheck resource in the given region.
    func `get`(
      project: Swift.String,
      region: Swift.String,
      compositeHealthCheck: Swift.String,
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheck

    /// Gets the most recent health check results for this
    /// regional CompositeHealthCheck.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_getHealth")
    func getHealth(request: Clients.RegionCompositeHealthChecksClient.GetHealthRequest) async throws
      -> GoogleCloudComputeV1.CompositeHealthCheckHealth

    /// Gets the most recent health check results for this
    /// regional CompositeHealthCheck.
    func getHealth(
      project: Swift.String,
      region: Swift.String,
      compositeHealthCheck: Swift.String,
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckHealth

    /// Create a CompositeHealthCheck in the specified project in the given region
    /// using the parameters that are included in the request.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_insert")
    func insert(request: Clients.RegionCompositeHealthChecksClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Create a CompositeHealthCheck in the specified project in the given region
    /// using the parameters that are included in the request.
    func insert(
      project: Swift.String,
      region: Swift.String,
      body: CompositeHealthCheck?,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Lists the CompositeHealthChecks for a project in the given region.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_list")
    func list(request: Clients.RegionCompositeHealthChecksClient.ListRequest) async throws
      -> GoogleCloudComputeV1.CompositeHealthCheckList

    /// Lists the CompositeHealthChecks for a project in the given region.
    func list(
      byItem: Clients.RegionCompositeHealthChecksClient.ListRequest
    ) throws -> any AsyncSequence<CompositeHealthCheck, Swift.Error>

    /// Lists the CompositeHealthChecks for a project in the given region.
    func list(
      project: Swift.String,
      region: Swift.String,
    ) throws -> any AsyncSequence<CompositeHealthCheck, Swift.Error>

    /// Updates the specified regional CompositeHealthCheck resource
    /// with the data included in the request.  This method supportsPATCH
    /// semantics and uses theJSON merge
    /// patch format and processing rules.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_patch")
    func patch(request: Clients.RegionCompositeHealthChecksClient.PatchRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Updates the specified regional CompositeHealthCheck resource
    /// with the data included in the request.  This method supportsPATCH
    /// semantics and uses theJSON merge
    /// patch format and processing rules.
    func patch(
      project: Swift.String,
      region: Swift.String,
      compositeHealthCheck: Swift.String,
      body: CompositeHealthCheck?,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns permissions that a caller has on the specified resource.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_testIamPermissions")
    func testIamPermissions(
      request: Clients.RegionCompositeHealthChecksClient.TestIamPermissionsRequest
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse

    /// Returns permissions that a caller has on the specified resource.
    func testIamPermissions(
      project: Swift.String,
      region: Swift.String,
      resource: Swift.String,
      body: TestPermissionsRequest?,
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse

    /// Retrieves the list of all CompositeHealthCheck resources (all
    /// regional) available to the specified project.
    ///
    /// To prevent failure, it is recommended that you set the
    /// `returnPartialSuccess` parameter to `true`.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_aggregatedList")
    func aggregatedList(
      request: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckAggregatedList

    /// Retrieves the list of all CompositeHealthCheck resources (all
    /// regional) available to the specified project.
    ///
    /// To prevent failure, it is recommended that you set the
    /// `returnPartialSuccess` parameter to `true`.
    func aggregatedList(
      byItem: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<(Swift.String, CompositeHealthChecksScopedList), Swift.Error>

    /// Deletes the specified CompositeHealthCheck in the given region
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_delete")
    func delete(
      request: Clients.RegionCompositeHealthChecksClient.DeleteRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns the specified CompositeHealthCheck resource in the given region.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_get")
    func `get`(
      request: Clients.RegionCompositeHealthChecksClient.GetRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheck

    /// Gets the most recent health check results for this
    /// regional CompositeHealthCheck.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_getHealth")
    func getHealth(
      request: Clients.RegionCompositeHealthChecksClient.GetHealthRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckHealth

    /// Create a CompositeHealthCheck in the specified project in the given region
    /// using the parameters that are included in the request.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_insert")
    func insert(
      request: Clients.RegionCompositeHealthChecksClient.InsertRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Lists the CompositeHealthChecks for a project in the given region.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_list")
    func list(
      request: Clients.RegionCompositeHealthChecksClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckList

    /// Lists the CompositeHealthChecks for a project in the given region.
    func list(
      byItem: Clients.RegionCompositeHealthChecksClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<CompositeHealthCheck, Swift.Error>

    /// Updates the specified regional CompositeHealthCheck resource
    /// with the data included in the request.  This method supportsPATCH
    /// semantics and uses theJSON merge
    /// patch format and processing rules.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_patch")
    func patch(
      request: Clients.RegionCompositeHealthChecksClient.PatchRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns permissions that a caller has on the specified resource.
    ///
    /// @Snippet(path: "regionCompositeHealthChecks_testIamPermissions")
    func testIamPermissions(
      request: Clients.RegionCompositeHealthChecksClient.TestIamPermissionsRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse
  }

  extension Clients {
    /// The recommended implementation for ``RegionCompositeHealthChecks``.
    public class RegionCompositeHealthChecksClient: RegionCompositeHealthChecks {
      let inner: any RegionCompositeHealthChecksStub

      /// Creates a new `RegionCompositeHealthChecksClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any RegionCompositeHealthChecksStub = try RegionCompositeHealthChecksTransport(
          options)
        inner = RegionCompositeHealthChecksRetry(inner, options: options)
        if let logger = options.logger {
          inner = RegionCompositeHealthChecksLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `RegionCompositeHealthChecks.aggregatedList`
      public func aggregatedList(
        request: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckAggregatedList {
        try await self.inner.aggregatedList(request: request, options: options)
      }

      /// Retrieves the list of all CompositeHealthCheck resources (all
      /// regional) available to the specified project.
      ///
      /// To prevent failure, it is recommended that you set the
      /// `returnPartialSuccess` parameter to `true`.
      public func aggregatedList(
        byItem: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest,
        options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<(Swift.String, CompositeHealthChecksScopedList), Swift.Error> {
        let listRpc = {
          (token: String) async throws -> GoogleCloudComputeV1.CompositeHealthCheckAggregatedList in
          var request = byItem
          request.pageToken = token
          return try await self.aggregatedList(request: request, options: options)
        }
        return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
      }

      /// See `RegionCompositeHealthChecks.delete`
      public func delete(
        request: Clients.RegionCompositeHealthChecksClient.DeleteRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.delete(request: request, options: options)
      }

      /// See `RegionCompositeHealthChecks.`get``
      public func `get`(
        request: Clients.RegionCompositeHealthChecksClient.GetRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.CompositeHealthCheck {
        try await self.inner.`get`(request: request, options: options)
      }

      /// See `RegionCompositeHealthChecks.getHealth`
      public func getHealth(
        request: Clients.RegionCompositeHealthChecksClient.GetHealthRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckHealth {
        try await self.inner.getHealth(request: request, options: options)
      }

      /// See `RegionCompositeHealthChecks.insert`
      public func insert(
        request: Clients.RegionCompositeHealthChecksClient.InsertRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.insert(request: request, options: options)
      }

      /// See `RegionCompositeHealthChecks.list`
      public func list(
        request: Clients.RegionCompositeHealthChecksClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckList {
        try await self.inner.list(request: request, options: options)
      }

      /// Lists the CompositeHealthChecks for a project in the given region.
      public func list(
        byItem: Clients.RegionCompositeHealthChecksClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<CompositeHealthCheck, Swift.Error> {
        let listRpc = {
          (token: String) async throws -> GoogleCloudComputeV1.CompositeHealthCheckList in
          var request = byItem
          request.pageToken = token
          return try await self.list(request: request, options: options)
        }
        return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
      }

      /// See `RegionCompositeHealthChecks.patch`
      public func patch(
        request: Clients.RegionCompositeHealthChecksClient.PatchRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.patch(request: request, options: options)
      }

      /// See `RegionCompositeHealthChecks.testIamPermissions`
      public func testIamPermissions(
        request: Clients.RegionCompositeHealthChecksClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self.inner.testIamPermissions(request: request, options: options)
      }
    }
  }

  // Default implementations
  extension RegionCompositeHealthChecks {
    public func aggregatedList(
      request: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckAggregatedList {
      try await self.aggregatedList(request: request, options: .init())
    }

    public func aggregatedList(
      request: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckAggregatedList {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func aggregatedList(
      byItem: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest
    ) throws -> any AsyncSequence<(Swift.String, CompositeHealthChecksScopedList), Swift.Error> {
      try self.aggregatedList(byItem: byItem, options: .init())
    }

    public func aggregatedList(
      byItem: Clients.RegionCompositeHealthChecksClient.AggregatedListRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<(Swift.String, CompositeHealthChecksScopedList), Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudComputeV1.CompositeHealthCheckAggregatedList in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func aggregatedList(
      project: Swift.String,
    ) throws -> any AsyncSequence<(Swift.String, CompositeHealthChecksScopedList), Swift.Error> {
      let request = Clients.RegionCompositeHealthChecksClient.AggregatedListRequest().with {
        $0.project = project
      }
      return try self.aggregatedList(byItem: request)
    }

    public func delete(request: Clients.RegionCompositeHealthChecksClient.DeleteRequest)
      async throws -> GoogleCloudComputeV1.Operation
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: Clients.RegionCompositeHealthChecksClient.DeleteRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func delete(
      project: Swift.String,
      region: Swift.String,
      compositeHealthCheck: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.RegionCompositeHealthChecksClient.DeleteRequest().with {
        $0.project = project
        $0.region = region
        $0.compositeHealthCheck = compositeHealthCheck
      }
      return try await self.delete(request: request)
    }

    public func `get`(request: Clients.RegionCompositeHealthChecksClient.GetRequest) async throws
      -> GoogleCloudComputeV1.CompositeHealthCheck
    {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: Clients.RegionCompositeHealthChecksClient.GetRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheck {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func `get`(
      project: Swift.String,
      region: Swift.String,
      compositeHealthCheck: Swift.String,
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheck {
      let request = Clients.RegionCompositeHealthChecksClient.GetRequest().with {
        $0.project = project
        $0.region = region
        $0.compositeHealthCheck = compositeHealthCheck
      }
      return try await self.`get`(request: request)
    }

    public func getHealth(request: Clients.RegionCompositeHealthChecksClient.GetHealthRequest)
      async throws -> GoogleCloudComputeV1.CompositeHealthCheckHealth
    {
      try await self.getHealth(request: request, options: .init())
    }

    public func getHealth(
      request: Clients.RegionCompositeHealthChecksClient.GetHealthRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckHealth {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getHealth(
      project: Swift.String,
      region: Swift.String,
      compositeHealthCheck: Swift.String,
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckHealth {
      let request = Clients.RegionCompositeHealthChecksClient.GetHealthRequest().with {
        $0.project = project
        $0.region = region
        $0.compositeHealthCheck = compositeHealthCheck
      }
      return try await self.getHealth(request: request)
    }

    public func insert(request: Clients.RegionCompositeHealthChecksClient.InsertRequest)
      async throws -> GoogleCloudComputeV1.Operation
    {
      try await self.insert(request: request, options: .init())
    }

    public func insert(
      request: Clients.RegionCompositeHealthChecksClient.InsertRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func insert(
      project: Swift.String,
      region: Swift.String,
      body: CompositeHealthCheck?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.RegionCompositeHealthChecksClient.InsertRequest().with {
        $0.project = project
        $0.region = region
        $0.body = body
      }
      return try await self.insert(request: request)
    }

    public func list(request: Clients.RegionCompositeHealthChecksClient.ListRequest) async throws
      -> GoogleCloudComputeV1.CompositeHealthCheckList
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: Clients.RegionCompositeHealthChecksClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.CompositeHealthCheckList {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(
      byItem: Clients.RegionCompositeHealthChecksClient.ListRequest
    ) throws -> any AsyncSequence<CompositeHealthCheck, Swift.Error> {
      try self.list(byItem: byItem, options: .init())
    }

    public func list(
      byItem: Clients.RegionCompositeHealthChecksClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<CompositeHealthCheck, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudComputeV1.CompositeHealthCheckList in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func list(
      project: Swift.String,
      region: Swift.String,
    ) throws -> any AsyncSequence<CompositeHealthCheck, Swift.Error> {
      let request = Clients.RegionCompositeHealthChecksClient.ListRequest().with {
        $0.project = project
        $0.region = region
      }
      return try self.list(byItem: request)
    }

    public func patch(request: Clients.RegionCompositeHealthChecksClient.PatchRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.patch(request: request, options: .init())
    }

    public func patch(
      request: Clients.RegionCompositeHealthChecksClient.PatchRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func patch(
      project: Swift.String,
      region: Swift.String,
      compositeHealthCheck: Swift.String,
      body: CompositeHealthCheck?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.RegionCompositeHealthChecksClient.PatchRequest().with {
        $0.project = project
        $0.region = region
        $0.compositeHealthCheck = compositeHealthCheck
        $0.body = body
      }
      return try await self.patch(request: request)
    }

    public func testIamPermissions(
      request: Clients.RegionCompositeHealthChecksClient.TestIamPermissionsRequest
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      try await self.testIamPermissions(request: request, options: .init())
    }

    public func testIamPermissions(
      request: Clients.RegionCompositeHealthChecksClient.TestIamPermissionsRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func testIamPermissions(
      project: Swift.String,
      region: Swift.String,
      resource: Swift.String,
      body: TestPermissionsRequest?,
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      let request = Clients.RegionCompositeHealthChecksClient.TestIamPermissionsRequest().with {
        $0.project = project
        $0.region = region
        $0.resource = resource
        $0.body = body
      }
      return try await self.testIamPermissions(request: request)
    }
  }
#endif
