// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if RegionTargetHttpProxies
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service for the `regionTargetHttpProxies` resource.
  ///
  /// @Snippet(path: "regionTargetHttpProxiesQuickstart")
  public protocol RegionTargetHttpProxies {
    /// Deletes the specified TargetHttpProxy resource.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_delete")
    func delete(request: Clients.RegionTargetHttpProxiesClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Deletes the specified TargetHttpProxy resource.
    func delete(
      project: Swift.String,
      region: Swift.String,
      targetHttpProxy: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns the specified TargetHttpProxy resource in the specified region.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_get")
    func `get`(request: Clients.RegionTargetHttpProxiesClient.GetRequest) async throws
      -> GoogleCloudComputeV1.TargetHttpProxy

    /// Returns the specified TargetHttpProxy resource in the specified region.
    func `get`(
      project: Swift.String,
      region: Swift.String,
      targetHttpProxy: Swift.String,
    ) async throws -> GoogleCloudComputeV1.TargetHttpProxy

    /// Creates a TargetHttpProxy resource in the specified project and region
    /// using the data included in the request.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_insert")
    func insert(request: Clients.RegionTargetHttpProxiesClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Creates a TargetHttpProxy resource in the specified project and region
    /// using the data included in the request.
    func insert(
      project: Swift.String,
      region: Swift.String,
      body: TargetHttpProxy?,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Retrieves the list of TargetHttpProxy resources available
    /// to the specified project in the specified region.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_list")
    func list(request: Clients.RegionTargetHttpProxiesClient.ListRequest) async throws
      -> GoogleCloudComputeV1.TargetHttpProxyList

    /// Retrieves the list of TargetHttpProxy resources available
    /// to the specified project in the specified region.
    func list(
      byItem: Clients.RegionTargetHttpProxiesClient.ListRequest
    ) throws -> any AsyncSequence<TargetHttpProxy, Swift.Error>

    /// Retrieves the list of TargetHttpProxy resources available
    /// to the specified project in the specified region.
    func list(
      project: Swift.String,
      region: Swift.String,
    ) throws -> any AsyncSequence<TargetHttpProxy, Swift.Error>

    /// Changes the URL map for TargetHttpProxy.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_setUrlMap")
    func setUrlMap(request: Clients.RegionTargetHttpProxiesClient.SetUrlMapRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Changes the URL map for TargetHttpProxy.
    func setUrlMap(
      project: Swift.String,
      region: Swift.String,
      targetHttpProxy: Swift.String,
      body: UrlMapReference?,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Deletes the specified TargetHttpProxy resource.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_delete")
    func delete(
      request: Clients.RegionTargetHttpProxiesClient.DeleteRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Returns the specified TargetHttpProxy resource in the specified region.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_get")
    func `get`(
      request: Clients.RegionTargetHttpProxiesClient.GetRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TargetHttpProxy

    /// Creates a TargetHttpProxy resource in the specified project and region
    /// using the data included in the request.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_insert")
    func insert(
      request: Clients.RegionTargetHttpProxiesClient.InsertRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Retrieves the list of TargetHttpProxy resources available
    /// to the specified project in the specified region.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_list")
    func list(
      request: Clients.RegionTargetHttpProxiesClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TargetHttpProxyList

    /// Retrieves the list of TargetHttpProxy resources available
    /// to the specified project in the specified region.
    func list(
      byItem: Clients.RegionTargetHttpProxiesClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TargetHttpProxy, Swift.Error>

    /// Changes the URL map for TargetHttpProxy.
    ///
    /// @Snippet(path: "regionTargetHttpProxies_setUrlMap")
    func setUrlMap(
      request: Clients.RegionTargetHttpProxiesClient.SetUrlMapRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation
  }

  extension Clients {
    /// The recommended implementation for ``RegionTargetHttpProxies``.
    public class RegionTargetHttpProxiesClient: RegionTargetHttpProxies {
      let inner: any RegionTargetHttpProxiesStub

      /// Creates a new `RegionTargetHttpProxiesClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any RegionTargetHttpProxiesStub = try RegionTargetHttpProxiesTransport(options)
        inner = RegionTargetHttpProxiesRetry(inner, options: options)
        if let logger = options.logger {
          inner = RegionTargetHttpProxiesLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `RegionTargetHttpProxies.delete`
      public func delete(
        request: Clients.RegionTargetHttpProxiesClient.DeleteRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.delete(request: request, options: options)
      }

      /// See `RegionTargetHttpProxies.`get``
      public func `get`(
        request: Clients.RegionTargetHttpProxiesClient.GetRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TargetHttpProxy {
        try await self.inner.`get`(request: request, options: options)
      }

      /// See `RegionTargetHttpProxies.insert`
      public func insert(
        request: Clients.RegionTargetHttpProxiesClient.InsertRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.insert(request: request, options: options)
      }

      /// See `RegionTargetHttpProxies.list`
      public func list(
        request: Clients.RegionTargetHttpProxiesClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TargetHttpProxyList {
        try await self.inner.list(request: request, options: options)
      }

      /// Retrieves the list of TargetHttpProxy resources available
      /// to the specified project in the specified region.
      public func list(
        byItem: Clients.RegionTargetHttpProxiesClient.ListRequest,
        options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<TargetHttpProxy, Swift.Error> {
        let listRpc = { (token: String) async throws -> GoogleCloudComputeV1.TargetHttpProxyList in
          var request = byItem
          request.pageToken = token
          return try await self.list(request: request, options: options)
        }
        return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
      }

      /// See `RegionTargetHttpProxies.setUrlMap`
      public func setUrlMap(
        request: Clients.RegionTargetHttpProxiesClient.SetUrlMapRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.setUrlMap(request: request, options: options)
      }
    }
  }

  // Default implementations
  extension RegionTargetHttpProxies {
    public func delete(request: Clients.RegionTargetHttpProxiesClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: Clients.RegionTargetHttpProxiesClient.DeleteRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func delete(
      project: Swift.String,
      region: Swift.String,
      targetHttpProxy: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.RegionTargetHttpProxiesClient.DeleteRequest().with {
        $0.project = project
        $0.region = region
        $0.targetHttpProxy = targetHttpProxy
      }
      return try await self.delete(request: request)
    }

    public func `get`(request: Clients.RegionTargetHttpProxiesClient.GetRequest) async throws
      -> GoogleCloudComputeV1.TargetHttpProxy
    {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: Clients.RegionTargetHttpProxiesClient.GetRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TargetHttpProxy {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func `get`(
      project: Swift.String,
      region: Swift.String,
      targetHttpProxy: Swift.String,
    ) async throws -> GoogleCloudComputeV1.TargetHttpProxy {
      let request = Clients.RegionTargetHttpProxiesClient.GetRequest().with {
        $0.project = project
        $0.region = region
        $0.targetHttpProxy = targetHttpProxy
      }
      return try await self.`get`(request: request)
    }

    public func insert(request: Clients.RegionTargetHttpProxiesClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.insert(request: request, options: .init())
    }

    public func insert(
      request: Clients.RegionTargetHttpProxiesClient.InsertRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func insert(
      project: Swift.String,
      region: Swift.String,
      body: TargetHttpProxy?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.RegionTargetHttpProxiesClient.InsertRequest().with {
        $0.project = project
        $0.region = region
        $0.body = body
      }
      return try await self.insert(request: request)
    }

    public func list(request: Clients.RegionTargetHttpProxiesClient.ListRequest) async throws
      -> GoogleCloudComputeV1.TargetHttpProxyList
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: Clients.RegionTargetHttpProxiesClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TargetHttpProxyList {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(
      byItem: Clients.RegionTargetHttpProxiesClient.ListRequest
    ) throws -> any AsyncSequence<TargetHttpProxy, Swift.Error> {
      try self.list(byItem: byItem, options: .init())
    }

    public func list(
      byItem: Clients.RegionTargetHttpProxiesClient.ListRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TargetHttpProxy, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudComputeV1.TargetHttpProxyList in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func list(
      project: Swift.String,
      region: Swift.String,
    ) throws -> any AsyncSequence<TargetHttpProxy, Swift.Error> {
      let request = Clients.RegionTargetHttpProxiesClient.ListRequest().with {
        $0.project = project
        $0.region = region
      }
      return try self.list(byItem: request)
    }

    public func setUrlMap(request: Clients.RegionTargetHttpProxiesClient.SetUrlMapRequest)
      async throws -> GoogleCloudComputeV1.Operation
    {
      try await self.setUrlMap(request: request, options: .init())
    }

    public func setUrlMap(
      request: Clients.RegionTargetHttpProxiesClient.SetUrlMapRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func setUrlMap(
      project: Swift.String,
      region: Swift.String,
      targetHttpProxy: Swift.String,
      body: UrlMapReference?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.RegionTargetHttpProxiesClient.SetUrlMapRequest().with {
        $0.project = project
        $0.region = region
        $0.targetHttpProxy = targetHttpProxy
        $0.body = body
      }
      return try await self.setUrlMap(request: request)
    }
  }
#endif
