// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Routers || Routes
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  public struct RouteAsPath: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// [Output Only] The AS numbers of the AS Path.
    public var asLists: [Swift.UInt32] = []

    /// [Output Only] The type of the AS Path, which can be one of the following
    /// values:
    /// - 'AS_SET': unordered set of autonomous systems that the route
    /// in has traversed
    /// - 'AS_SEQUENCE': ordered set of autonomous
    /// systems that the route has traversed
    /// - 'AS_CONFED_SEQUENCE':
    /// ordered set of Member Autonomous Systems in the local confederation that
    /// the route has traversed
    /// - 'AS_CONFED_SET': unordered set of
    /// Member Autonomous Systems in the local confederation that the route has
    /// traversed
    public var pathSegmentType: RouteAsPath.PathSegmentType? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RouteAsPath`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RouteAsPath().with { $0.asLists = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let asLists = CodingKeys(stringValue: "asLists")
      static let pathSegmentType = CodingKeys(stringValue: "pathSegmentType")

      static let _knownKeys: Set<Swift.String> = [
        "asLists",
        "pathSegmentType",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.UInt32].self, forKey: .asLists) {
        self.asLists = value
      }
      self.pathSegmentType = try container.decodeIfPresent(
        RouteAsPath.PathSegmentType.self, forKey: .pathSegmentType)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.asLists, forKey: .asLists)
      try container.encodeIfPresent(self.pathSegmentType, forKey: .pathSegmentType)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [pathSegmentType][google.cloud.compute.v1.RouteAsPath.pathSegmentType] field.
    ///
    /// [google.cloud.compute.v1.RouteAsPath.pathSegmentType]: <doc:RouteAsPath/PathSegmentType>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum PathSegmentType: Codable, Equatable, Sendable {
      case asConfedSequence
      case asConfedSet
      case asSequence
      case asSet
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .asConfedSequence: return "AS_CONFED_SEQUENCE"
        case .asConfedSet: return "AS_CONFED_SET"
        case .asSequence: return "AS_SEQUENCE"
        case .asSet: return "AS_SET"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PathSegmentType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "AS_CONFED_SEQUENCE": self = .asConfedSequence
        case "AS_CONFED_SET": self = .asConfedSet
        case "AS_SEQUENCE": self = .asSequence
        case "AS_SET": self = .asSet
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .asConfedSequence: return try container.encode("AS_CONFED_SEQUENCE")
        case .asConfedSet: return try container.encode("AS_CONFED_SET")
        case .asSequence: return try container.encode("AS_SEQUENCE")
        case .asSet: return try container.encode("AS_SET")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.RouteAsPath"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
