// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if OrganizationSecurityPolicies || RegionSecurityPolicies || SecurityPolicies
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  public struct SecurityPolicyDdosProtectionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var ddosAdaptiveProtection: SecurityPolicyDdosProtectionConfig.DdosAdaptiveProtection? =
      nil

    /// DDoS Protection for Network Load Balancers (and VMs with public IPs)
    /// builds DDoS mitigations that minimize collateral damage. It quantifies
    /// this as the fraction of a non-abuse baseline that's inadvertently
    /// blocked.
    ///
    /// Rules whose collateral damage exceeds ddosImpactedBaselineThreshold will
    /// not be deployed. Using a lower value will prioritize keeping collateral
    /// damage low, possibly at the cost of its effectiveness in rate limiting
    /// some or all of the attack. It should typically be unset, so Advanced DDoS
    /// (and Adaptive Protection) uses the best mitigation it can find. Setting
    /// the threshold is advised if there are logs for false positive detections
    /// with high collateral damage, and will cause Advanced DDoS to attempt to
    /// find a less aggressive rule that satisfies the constraint. If a suitable
    /// rule cannot be found, the system falls back to either no mitigation for
    /// smaller attacks or broader network throttles for larger ones.
    public var ddosImpactedBaselineThreshold: Swift.Float? = nil

    public var ddosProtection: SecurityPolicyDdosProtectionConfig.DdosProtection? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SecurityPolicyDdosProtectionConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SecurityPolicyDdosProtectionConfig().with { $0.ddosAdaptiveProtection = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ddosAdaptiveProtection = CodingKeys(stringValue: "ddosAdaptiveProtection")
      static let ddosImpactedBaselineThreshold = CodingKeys(
        stringValue: "ddosImpactedBaselineThreshold")
      static let ddosProtection = CodingKeys(stringValue: "ddosProtection")

      static let _knownKeys: Set<Swift.String> = [
        "ddosAdaptiveProtection",
        "ddosImpactedBaselineThreshold",
        "ddosProtection",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.ddosAdaptiveProtection = try container.decodeIfPresent(
        SecurityPolicyDdosProtectionConfig.DdosAdaptiveProtection.self,
        forKey: .ddosAdaptiveProtection)
      self.ddosImpactedBaselineThreshold = try container.decodeIfPresent(
        Swift.Float.self, forKey: .ddosImpactedBaselineThreshold)
      self.ddosProtection = try container.decodeIfPresent(
        SecurityPolicyDdosProtectionConfig.DdosProtection.self, forKey: .ddosProtection)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.ddosAdaptiveProtection, forKey: .ddosAdaptiveProtection)
      try container.encodeIfPresent(
        self.ddosImpactedBaselineThreshold, forKey: .ddosImpactedBaselineThreshold)
      try container.encodeIfPresent(self.ddosProtection, forKey: .ddosProtection)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [ddosAdaptiveProtection][google.cloud.compute.v1.SecurityPolicyDdosProtectionConfig.ddosAdaptiveProtection] field.
    ///
    /// [google.cloud.compute.v1.SecurityPolicyDdosProtectionConfig.ddosAdaptiveProtection]: <doc:SecurityPolicyDdosProtectionConfig/DdosAdaptiveProtection>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum DdosAdaptiveProtection: Codable, Equatable, Sendable {
      case unspecified
      case disabled
      case enabled
      case preview
      @available(*, deprecated)
      case unspecifiedAdaptiveProtection
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "DDOS_ADAPTIVE_PROTECTION_UNSPECIFIED"
        case .disabled: return "DISABLED"
        case .enabled: return "ENABLED"
        case .preview: return "PREVIEW"
        case .unspecifiedAdaptiveProtection: return "UNSPECIFIED_ADAPTIVE_PROTECTION"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DdosAdaptiveProtection/unknownStringValue(_:)).
      #if hasAttribute(diagnose)
        @diagnose(DeprecatedDeclaration, as: ignored)
      #endif
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "DDOS_ADAPTIVE_PROTECTION_UNSPECIFIED": self = .unspecified
        case "DISABLED": self = .disabled
        case "ENABLED": self = .enabled
        case "PREVIEW": self = .preview
        case "UNSPECIFIED_ADAPTIVE_PROTECTION": self = .unspecifiedAdaptiveProtection
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("DDOS_ADAPTIVE_PROTECTION_UNSPECIFIED")
        case .disabled: return try container.encode("DISABLED")
        case .enabled: return try container.encode("ENABLED")
        case .preview: return try container.encode("PREVIEW")
        case .unspecifiedAdaptiveProtection:
          return try container.encode("UNSPECIFIED_ADAPTIVE_PROTECTION")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The enumerated type for the [ddosProtection][google.cloud.compute.v1.SecurityPolicyDdosProtectionConfig.ddosProtection] field.
    ///
    /// [google.cloud.compute.v1.SecurityPolicyDdosProtectionConfig.ddosProtection]: <doc:SecurityPolicyDdosProtectionConfig/DdosProtection>
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum DdosProtection: Codable, Equatable, Sendable {
      case advanced
      case advancedPreview
      case standard
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(Swift.String)

      /// Returns the string value (or name) associated with the enumeration.
      public var stringValue: Swift.String? {
        switch self {
        case .advanced: return "ADVANCED"
        case .advancedPreview: return "ADVANCED_PREVIEW"
        case .standard: return "STANDARD"
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DdosProtection/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ADVANCED": self = .advanced
        case "ADVANCED_PREVIEW": self = .advancedPreview
        case "STANDARD": self = .standard
        default: self = .unknownStringValue(stringValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let s = try container.decode(Swift.String.self)
        self.init(stringValue: s)
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .advanced: return try container.encode("ADVANCED")
        case .advancedPreview: return try container.encode("ADVANCED_PREVIEW")
        case .standard: return try container.encode("STANDARD")
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.SecurityPolicyDdosProtectionConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
