// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if StoragePools
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWKT
  @_spi(GoogleCloudInternal) import GoogleCloudGax

  extension Clients {
    final class StoragePoolsRetry: StoragePoolsStub {
      let inner: any StoragePoolsStub
      let options: GoogleCloudGax.ClientOptions

      public init(_ inner: any StoragePoolsStub, options: GoogleCloudGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func aggregatedList(
        request: StoragePoolsClient.AggregatedListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.StoragePoolAggregatedList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: StoragePoolsClient.AggregatedListRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.StoragePoolAggregatedList
            in
            return try await self.inner.aggregatedList(request: r, options: o)
          })
      }

      public func delete(
        request: StoragePoolsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: StoragePoolsClient.DeleteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func `get`(
        request: StoragePoolsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.StoragePool {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: StoragePoolsClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.StoragePool
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func getIamPolicy(
        request: StoragePoolsClient.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: StoragePoolsClient.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Policy
            in
            return try await self.inner.getIamPolicy(request: r, options: o)
          })
      }

      public func insert(
        request: StoragePoolsClient.InsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: StoragePoolsClient.InsertRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: StoragePoolsClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.StoragePoolList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: StoragePoolsClient.ListRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.StoragePoolList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func listDisks(
        request: StoragePoolsClient.ListDisksRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.StoragePoolListDisks {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: StoragePoolsClient.ListDisksRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.StoragePoolListDisks
            in
            return try await self.inner.listDisks(request: r, options: o)
          })
      }

      public func setIamPolicy(
        request: StoragePoolsClient.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Policy {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: StoragePoolsClient.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Policy
            in
            return try await self.inner.setIamPolicy(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: StoragePoolsClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: StoragePoolsClient.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.TestPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }

      public func update(
        request: StoragePoolsClient.UpdateRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: StoragePoolsClient.UpdateRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.update(request: r, options: o)
          })
      }

      public func getOperation(
        request: ZoneOperationsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ZoneOperationsClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }
    }
  }
#endif
