// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TargetPools
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  extension Clients {
    final class TargetPoolsRetry: TargetPoolsStub {
      let inner: any TargetPoolsStub
      let options: GoogleCloudGax.ClientOptions

      public init(_ inner: any TargetPoolsStub, options: GoogleCloudGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func addHealthCheck(
        request: Clients.TargetPoolsClient.AddHealthCheckRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.TargetPoolsClient.AddHealthCheckRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.addHealthCheck(request: r, options: o)
          })
      }

      public func addInstance(
        request: Clients.TargetPoolsClient.AddInstanceRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.TargetPoolsClient.AddInstanceRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.addInstance(request: r, options: o)
          })
      }

      public func aggregatedList(
        request: Clients.TargetPoolsClient.AggregatedListRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TargetPoolAggregatedList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: Clients.TargetPoolsClient.AggregatedListRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.TargetPoolAggregatedList
            in
            return try await self.inner.aggregatedList(request: r, options: o)
          })
      }

      public func delete(
        request: Clients.TargetPoolsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.TargetPoolsClient.DeleteRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.delete(request: r, options: o)
          })
      }

      public func `get`(
        request: Clients.TargetPoolsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TargetPool {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: Clients.TargetPoolsClient.GetRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudComputeV1.TargetPool
            in
            return try await self.inner.`get`(request: r, options: o)
          })
      }

      public func getHealth(
        request: Clients.TargetPoolsClient.GetHealthRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TargetPoolInstanceHealth {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.TargetPoolsClient.GetHealthRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.TargetPoolInstanceHealth
            in
            return try await self.inner.getHealth(request: r, options: o)
          })
      }

      public func insert(
        request: Clients.TargetPoolsClient.InsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.TargetPoolsClient.InsertRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.insert(request: r, options: o)
          })
      }

      public func list(
        request: Clients.TargetPoolsClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TargetPoolList {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: Clients.TargetPoolsClient.ListRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.TargetPoolList
            in
            return try await self.inner.list(request: r, options: o)
          })
      }

      public func removeHealthCheck(
        request: Clients.TargetPoolsClient.RemoveHealthCheckRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (
              r: Clients.TargetPoolsClient.RemoveHealthCheckRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.removeHealthCheck(request: r, options: o)
          })
      }

      public func removeInstance(
        request: Clients.TargetPoolsClient.RemoveInstanceRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.TargetPoolsClient.RemoveInstanceRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.removeInstance(request: r, options: o)
          })
      }

      public func setBackup(
        request: Clients.TargetPoolsClient.SetBackupRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: Clients.TargetPoolsClient.SetBackupRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.setBackup(request: r, options: o)
          })
      }

      public func setSecurityPolicy(
        request: Clients.TargetPoolsClient.SetSecurityPolicyRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (
              r: Clients.TargetPoolsClient.SetSecurityPolicyRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.Operation
            in
            return try await self.inner.setSecurityPolicy(request: r, options: o)
          })
      }

      public func testIamPermissions(
        request: Clients.TargetPoolsClient.TestIamPermissionsRequest,
        options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (
              r: Clients.TargetPoolsClient.TestIamPermissionsRequest,
              o: GoogleCloudGax.RequestOptions
            ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse
            in
            return try await self.inner.testIamPermissions(request: r, options: o)
          })
      }
    }
  }
#endif
