// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TargetSslProxies
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Service for the `targetSslProxies` resource.
  ///
  /// @Snippet(path: "targetSslProxiesQuickstart")
  public final class TargetSslProxiesClient: Clients.TargetSslProxiesProtocol, Sendable {
    let inner: any Clients.TargetSslProxiesStub
    let pollingErrorPolicy: any GoogleGax.PollingErrorPolicy
    let pollingBackoffPolicy: any GoogleGax.PollingBackoffPolicy

    /// Creates a new `TargetSslProxiesClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.TargetSslProxiesStub = try Clients.TargetSslProxiesTransport(options)
      inner = Clients.TargetSslProxiesRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.TargetSslProxiesLogging(inner, logger: logger)
      }
      self.inner = inner
      self.pollingErrorPolicy = options.pollingErrorPolicy
      self.pollingBackoffPolicy = options.pollingBackoffPolicy
    }

    /// Deletes the specified TargetSslProxy resource.
    ///
    /// @Snippet(path: "targetSslProxies_delete")
    public func delete(
      request: TargetSslProxiesClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.delete(request: request, options: options)
    }

    /// Deletes the specified TargetSslProxy resource.
    ///
    /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
    ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
    ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
    ///   method once the operation completes.
    ///
    /// @Snippet(path: "targetSslProxies_delete")
    public func deletePollingUntilDone(
      request: TargetSslProxiesClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.delete(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
          }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
      return try await poller.wait()
    }

    /// Returns the specified TargetSslProxy resource.
    ///
    /// @Snippet(path: "targetSslProxies_get")
    public func `get`(
      request: TargetSslProxiesClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TargetSslProxy {
      try await self.inner.`get`(request: request, options: options)
    }

    /// Creates a TargetSslProxy resource in the specified project using
    /// the data included in the request.
    ///
    /// @Snippet(path: "targetSslProxies_insert")
    public func insert(
      request: TargetSslProxiesClient.InsertRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.insert(request: request, options: options)
    }

    /// Creates a TargetSslProxy resource in the specified project using
    /// the data included in the request.
    ///
    /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
    ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
    ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
    ///   method once the operation completes.
    ///
    /// @Snippet(path: "targetSslProxies_insert")
    public func insertPollingUntilDone(
      request: TargetSslProxiesClient.InsertRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.insert(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
          }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
      return try await poller.wait()
    }

    /// Retrieves the list of TargetSslProxy resources
    /// available to the specified project.
    ///
    /// @Snippet(path: "targetSslProxies_list")
    public func list(
      request: TargetSslProxiesClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TargetSslProxyList {
      try await self.inner.list(request: request, options: options)
    }

    /// Changes the BackendService for TargetSslProxy.
    ///
    /// @Snippet(path: "targetSslProxies_setBackendService")
    public func setBackendService(
      request: TargetSslProxiesClient.SetBackendServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.setBackendService(request: request, options: options)
    }

    /// Changes the BackendService for TargetSslProxy.
    ///
    /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
    ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
    ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
    ///   method once the operation completes.
    ///
    /// @Snippet(path: "targetSslProxies_setBackendService")
    public func setBackendServicePollingUntilDone(
      request: TargetSslProxiesClient.SetBackendServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.setBackendService(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
          }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
      return try await poller.wait()
    }

    /// Changes the Certificate Map for TargetSslProxy.
    ///
    /// @Snippet(path: "targetSslProxies_setCertificateMap")
    public func setCertificateMap(
      request: TargetSslProxiesClient.SetCertificateMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.setCertificateMap(request: request, options: options)
    }

    /// Changes the Certificate Map for TargetSslProxy.
    ///
    /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
    ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
    ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
    ///   method once the operation completes.
    ///
    /// @Snippet(path: "targetSslProxies_setCertificateMap")
    public func setCertificateMapPollingUntilDone(
      request: TargetSslProxiesClient.SetCertificateMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.setCertificateMap(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
          }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
      return try await poller.wait()
    }

    /// Changes the ProxyHeaderType for TargetSslProxy.
    ///
    /// @Snippet(path: "targetSslProxies_setProxyHeader")
    public func setProxyHeader(
      request: TargetSslProxiesClient.SetProxyHeaderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.setProxyHeader(request: request, options: options)
    }

    /// Changes the ProxyHeaderType for TargetSslProxy.
    ///
    /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
    ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
    ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
    ///   method once the operation completes.
    ///
    /// @Snippet(path: "targetSslProxies_setProxyHeader")
    public func setProxyHeaderPollingUntilDone(
      request: TargetSslProxiesClient.SetProxyHeaderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.setProxyHeader(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
          }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
      return try await poller.wait()
    }

    /// Changes SslCertificates for TargetSslProxy.
    ///
    /// @Snippet(path: "targetSslProxies_setSslCertificates")
    public func setSslCertificates(
      request: TargetSslProxiesClient.SetSslCertificatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.setSslCertificates(request: request, options: options)
    }

    /// Changes SslCertificates for TargetSslProxy.
    ///
    /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
    ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
    ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
    ///   method once the operation completes.
    ///
    /// @Snippet(path: "targetSslProxies_setSslCertificates")
    public func setSslCertificatesPollingUntilDone(
      request: TargetSslProxiesClient.SetSslCertificatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.setSslCertificates(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
          }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
      return try await poller.wait()
    }

    /// Sets the SSL policy for TargetSslProxy. The SSL policy specifies the
    /// server-side support for SSL features. This affects connections between
    /// clients and the load balancer. They do not affect the
    /// connection between the load balancer and the backends.
    ///
    /// @Snippet(path: "targetSslProxies_setSslPolicy")
    public func setSslPolicy(
      request: TargetSslProxiesClient.SetSslPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.setSslPolicy(request: request, options: options)
    }

    /// Sets the SSL policy for TargetSslProxy. The SSL policy specifies the
    /// server-side support for SSL features. This affects connections between
    /// clients and the load balancer. They do not affect the
    /// connection between the load balancer and the backends.
    ///
    /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
    ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
    ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
    ///   method once the operation completes.
    ///
    /// @Snippet(path: "targetSslProxies_setSslPolicy")
    public func setSslPolicyPollingUntilDone(
      request: TargetSslProxiesClient.SetSslPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      let extractStatus = {
        @Sendable (op: GoogleCloudComputeV1.Operation) throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        guard op._done() else {
          return .init(done: false, result: nil)
        }

        do {
          try op._detectErrors()
        } catch let e as GoogleGax.RequestError {
          return .init(done: true, result: .failure(e))
        }
        return .init(done: true, result: .success(op))
      }
      let rawOp = try await self.setSslPolicy(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws
          -> GoogleGax._PollableOperationImpl<GoogleCloudComputeV1.Operation>.State in
        let op = try await self.getOperation(
          request: .init().with {
            $0.operation = rawOp._name()
            $0.project = request.project
          }, options: options)
        return try extractStatus(op)
      }
      let poller = GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll
      )
      return try await poller.wait()
    }

    /// Returns permissions that a caller has on the specified resource.
    ///
    /// @Snippet(path: "targetSslProxies_testIamPermissions")
    public func testIamPermissions(
      request: TargetSslProxiesClient.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// Retrieves the specified Operations resource.
    ///
    /// @Snippet(path: "targetSslProxies_getOperation")
    func getOperation(
      request: GlobalOperationsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `TargetSslProxiesClient`.
    ///
    /// To mock `TargetSslProxiesClient` change your functions to receive
    /// `some TargetSslProxiesProtocol` or `any TargetSslProxiesProtocol`
    /// and pass a mock implementation in your tests.
    public protocol TargetSslProxiesProtocol: Sendable {
      /// See `TargetSslProxiesClient.delete`.
      func delete(
        request: TargetSslProxiesClient.DeleteRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.delete`.
      ///
      /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
      ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
      ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
      ///   method once the operation completes.
      func deletePollingUntilDone(
        request: TargetSslProxiesClient.DeleteRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.`get``.
      func `get`(
        request: TargetSslProxiesClient.GetRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TargetSslProxy

      /// See `TargetSslProxiesClient.insert`.
      func insert(
        request: TargetSslProxiesClient.InsertRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.insert`.
      ///
      /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
      ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
      ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
      ///   method once the operation completes.
      func insertPollingUntilDone(
        request: TargetSslProxiesClient.InsertRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.list`.
      func list(
        request: TargetSslProxiesClient.ListRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TargetSslProxyList

      /// See `TargetSslProxiesClient.setBackendService`.
      func setBackendService(
        request: TargetSslProxiesClient.SetBackendServiceRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setBackendService`.
      ///
      /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
      ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
      ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
      ///   method once the operation completes.
      func setBackendServicePollingUntilDone(
        request: TargetSslProxiesClient.SetBackendServiceRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setCertificateMap`.
      func setCertificateMap(
        request: TargetSslProxiesClient.SetCertificateMapRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setCertificateMap`.
      ///
      /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
      ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
      ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
      ///   method once the operation completes.
      func setCertificateMapPollingUntilDone(
        request: TargetSslProxiesClient.SetCertificateMapRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setProxyHeader`.
      func setProxyHeader(
        request: TargetSslProxiesClient.SetProxyHeaderRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setProxyHeader`.
      ///
      /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
      ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
      ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
      ///   method once the operation completes.
      func setProxyHeaderPollingUntilDone(
        request: TargetSslProxiesClient.SetProxyHeaderRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setSslCertificates`.
      func setSslCertificates(
        request: TargetSslProxiesClient.SetSslCertificatesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setSslCertificates`.
      ///
      /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
      ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
      ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
      ///   method once the operation completes.
      func setSslCertificatesPollingUntilDone(
        request: TargetSslProxiesClient.SetSslCertificatesRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setSslPolicy`.
      func setSslPolicy(
        request: TargetSslProxiesClient.SetSslPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.setSslPolicy`.
      ///
      /// - Note: Unlike standard gRPC long-running operations where polling returns the resulting
      ///   resource, Discovery-based operations return the terminal `GoogleCloudComputeV1.Operation`
      ///   status object. To obtain the created or modified resource, invoke the corresponding `get`
      ///   method once the operation completes.
      func setSslPolicyPollingUntilDone(
        request: TargetSslProxiesClient.SetSslPolicyRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      /// See `TargetSslProxiesClient.testIamPermissions`.
      func testIamPermissions(
        request: TargetSslProxiesClient.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse
    }
  }

  // Default implementations
  extension Clients.TargetSslProxiesProtocol {
    public func delete(request: TargetSslProxiesClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: TargetSslProxiesClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deletePollingUntilDone(
      request: TargetSslProxiesClient.DeleteRequest
    ) async throws -> GoogleCloudComputeV1.Operation {
      return try await self.deletePollingUntilDone(request: request, options: .init())
    }

    public func deletePollingUntilDone(
      request: TargetSslProxiesClient.DeleteRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deletePollingUntilDone(
      project: Swift.String,
      targetSslProxy: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = TargetSslProxiesClient.DeleteRequest().with {
        $0.project = project
        $0.targetSslProxy = targetSslProxy
      }
      return try await self.deletePollingUntilDone(request: request)
    }

    public func `get`(request: TargetSslProxiesClient.GetRequest) async throws
      -> GoogleCloudComputeV1.TargetSslProxy
    {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: TargetSslProxiesClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TargetSslProxy {
      throw GoogleGax.RequestError.unimplemented
    }

    public func `get`(
      project: Swift.String,
      targetSslProxy: Swift.String,
    ) async throws -> GoogleCloudComputeV1.TargetSslProxy {
      let request = TargetSslProxiesClient.GetRequest().with {
        $0.project = project
        $0.targetSslProxy = targetSslProxy
      }
      return try await self.`get`(request: request)
    }

    public func insert(request: TargetSslProxiesClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.insert(request: request, options: .init())
    }

    public func insert(
      request: TargetSslProxiesClient.InsertRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func insertPollingUntilDone(
      request: TargetSslProxiesClient.InsertRequest
    ) async throws -> GoogleCloudComputeV1.Operation {
      return try await self.insertPollingUntilDone(request: request, options: .init())
    }

    public func insertPollingUntilDone(
      request: TargetSslProxiesClient.InsertRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func insertPollingUntilDone(
      project: Swift.String,
      body: TargetSslProxy?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = TargetSslProxiesClient.InsertRequest().with {
        $0.project = project
        $0.body = body
      }
      return try await self.insertPollingUntilDone(request: request)
    }

    public func list(request: TargetSslProxiesClient.ListRequest) async throws
      -> GoogleCloudComputeV1.TargetSslProxyList
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: TargetSslProxiesClient.ListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TargetSslProxyList {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listByItems(
      request: TargetSslProxiesClient.ListRequest
    ) -> some AsyncSequence<TargetSslProxy, any Swift.Error> & Sendable {
      self.listByItems(request: request, options: .init())
    }

    /// Retrieves the list of TargetSslProxy resources
    /// available to the specified project.
    ///
    /// @Snippet(path: "targetSslProxies_list")
    public func listByItems(
      request: TargetSslProxiesClient.ListRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<TargetSslProxy, any Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudComputeV1.TargetSslProxyList in
        var request = request
        request.pageToken = token
        return try await self.list(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(
        listRpc: listRpc, initialPageToken: request.pageToken)
    }

    public func listByItems(
      project: Swift.String,
    ) -> some AsyncSequence<TargetSslProxy, any Swift.Error> & Sendable {
      let request = TargetSslProxiesClient.ListRequest().with {
        $0.project = project
      }
      return self.listByItems(request: request)
    }

    public func setBackendService(request: TargetSslProxiesClient.SetBackendServiceRequest)
      async throws -> GoogleCloudComputeV1.Operation
    {
      try await self.setBackendService(request: request, options: .init())
    }

    public func setBackendService(
      request: TargetSslProxiesClient.SetBackendServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setBackendServicePollingUntilDone(
      request: TargetSslProxiesClient.SetBackendServiceRequest
    ) async throws -> GoogleCloudComputeV1.Operation {
      return try await self.setBackendServicePollingUntilDone(request: request, options: .init())
    }

    public func setBackendServicePollingUntilDone(
      request: TargetSslProxiesClient.SetBackendServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setBackendServicePollingUntilDone(
      project: Swift.String,
      targetSslProxy: Swift.String,
      body: TargetSslProxiesSetBackendServiceRequest?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = TargetSslProxiesClient.SetBackendServiceRequest().with {
        $0.project = project
        $0.targetSslProxy = targetSslProxy
        $0.body = body
      }
      return try await self.setBackendServicePollingUntilDone(request: request)
    }

    public func setCertificateMap(request: TargetSslProxiesClient.SetCertificateMapRequest)
      async throws -> GoogleCloudComputeV1.Operation
    {
      try await self.setCertificateMap(request: request, options: .init())
    }

    public func setCertificateMap(
      request: TargetSslProxiesClient.SetCertificateMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setCertificateMapPollingUntilDone(
      request: TargetSslProxiesClient.SetCertificateMapRequest
    ) async throws -> GoogleCloudComputeV1.Operation {
      return try await self.setCertificateMapPollingUntilDone(request: request, options: .init())
    }

    public func setCertificateMapPollingUntilDone(
      request: TargetSslProxiesClient.SetCertificateMapRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setCertificateMapPollingUntilDone(
      project: Swift.String,
      targetSslProxy: Swift.String,
      body: TargetSslProxiesSetCertificateMapRequest?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = TargetSslProxiesClient.SetCertificateMapRequest().with {
        $0.project = project
        $0.targetSslProxy = targetSslProxy
        $0.body = body
      }
      return try await self.setCertificateMapPollingUntilDone(request: request)
    }

    public func setProxyHeader(request: TargetSslProxiesClient.SetProxyHeaderRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.setProxyHeader(request: request, options: .init())
    }

    public func setProxyHeader(
      request: TargetSslProxiesClient.SetProxyHeaderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setProxyHeaderPollingUntilDone(
      request: TargetSslProxiesClient.SetProxyHeaderRequest
    ) async throws -> GoogleCloudComputeV1.Operation {
      return try await self.setProxyHeaderPollingUntilDone(request: request, options: .init())
    }

    public func setProxyHeaderPollingUntilDone(
      request: TargetSslProxiesClient.SetProxyHeaderRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setProxyHeaderPollingUntilDone(
      project: Swift.String,
      targetSslProxy: Swift.String,
      body: TargetSslProxiesSetProxyHeaderRequest?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = TargetSslProxiesClient.SetProxyHeaderRequest().with {
        $0.project = project
        $0.targetSslProxy = targetSslProxy
        $0.body = body
      }
      return try await self.setProxyHeaderPollingUntilDone(request: request)
    }

    public func setSslCertificates(request: TargetSslProxiesClient.SetSslCertificatesRequest)
      async throws -> GoogleCloudComputeV1.Operation
    {
      try await self.setSslCertificates(request: request, options: .init())
    }

    public func setSslCertificates(
      request: TargetSslProxiesClient.SetSslCertificatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setSslCertificatesPollingUntilDone(
      request: TargetSslProxiesClient.SetSslCertificatesRequest
    ) async throws -> GoogleCloudComputeV1.Operation {
      return try await self.setSslCertificatesPollingUntilDone(request: request, options: .init())
    }

    public func setSslCertificatesPollingUntilDone(
      request: TargetSslProxiesClient.SetSslCertificatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setSslCertificatesPollingUntilDone(
      project: Swift.String,
      targetSslProxy: Swift.String,
      body: TargetSslProxiesSetSslCertificatesRequest?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = TargetSslProxiesClient.SetSslCertificatesRequest().with {
        $0.project = project
        $0.targetSslProxy = targetSslProxy
        $0.body = body
      }
      return try await self.setSslCertificatesPollingUntilDone(request: request)
    }

    public func setSslPolicy(request: TargetSslProxiesClient.SetSslPolicyRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.setSslPolicy(request: request, options: .init())
    }

    public func setSslPolicy(
      request: TargetSslProxiesClient.SetSslPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setSslPolicyPollingUntilDone(
      request: TargetSslProxiesClient.SetSslPolicyRequest
    ) async throws -> GoogleCloudComputeV1.Operation {
      return try await self.setSslPolicyPollingUntilDone(request: request, options: .init())
    }

    public func setSslPolicyPollingUntilDone(
      request: TargetSslProxiesClient.SetSslPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func setSslPolicyPollingUntilDone(
      project: Swift.String,
      targetSslProxy: Swift.String,
      body: SslPolicyReference?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = TargetSslProxiesClient.SetSslPolicyRequest().with {
        $0.project = project
        $0.targetSslProxy = targetSslProxy
        $0.body = body
      }
      return try await self.setSslPolicyPollingUntilDone(request: request)
    }

    public func testIamPermissions(request: TargetSslProxiesClient.TestIamPermissionsRequest)
      async throws -> GoogleCloudComputeV1.TestPermissionsResponse
    {
      try await self.testIamPermissions(request: request, options: .init())
    }

    public func testIamPermissions(
      request: TargetSslProxiesClient.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func testIamPermissions(
      project: Swift.String,
      resource: Swift.String,
      body: TestPermissionsRequest?,
    ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse {
      let request = TargetSslProxiesClient.TestIamPermissionsRequest().with {
        $0.project = project
        $0.resource = resource
        $0.body = body
      }
      return try await self.testIamPermissions(request: request)
    }

    public func getOperation(request: GlobalOperationsClient.GetRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GlobalOperationsClient.GetRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleGax.RequestError.unimplemented
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'TargetSslProxies' trait in Package.swift to use this client."
  )
  public final class TargetSslProxiesClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'TargetSslProxies' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
