// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Subnetworks
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Secondary IP range of a usable subnetwork.
  public struct UsableSubnetworkSecondaryRange: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The range of IP addresses belonging to this subnetwork secondary range.
    /// Can be Ipv4 or Ipv6 range.
    public var ipCidrRange: Swift.String? = nil

    /// The name associated with this subnetwork secondary range, used when adding
    /// an alias IP range to a VM instance.
    /// The name must be 1-63 characters long, and comply withRFC1035.
    /// The name must be unique within the subnetwork.
    public var rangeName: Swift.String? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UsableSubnetworkSecondaryRange`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UsableSubnetworkSecondaryRange().with { $0.ipCidrRange = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ipCidrRange = CodingKeys(stringValue: "ipCidrRange")
      static let rangeName = CodingKeys(stringValue: "rangeName")

      static let _knownKeys: Set<Swift.String> = [
        "ipCidrRange",
        "rangeName",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.ipCidrRange = try container.decodeIfPresent(Swift.String.self, forKey: .ipCidrRange)
      self.rangeName = try container.decodeIfPresent(Swift.String.self, forKey: .rangeName)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.ipCidrRange, forKey: .ipCidrRange)
      try container.encodeIfPresent(self.rangeName, forKey: .rangeName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.UsableSubnetworkSecondaryRange"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
