// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if VpnGateways
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Represents a HA VPN gateway.
  ///
  /// HA VPN is a high-availability (HA) Cloud VPN solution that lets you securely
  /// connect your on-premises network to your Google Cloud Virtual Private Cloud
  /// network through an IPsec VPN connection in a single region.
  /// For more information about Cloud HA VPN solutions, see
  /// Cloud VPN topologies .
  public struct VpnGateway: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. [Output Only] Creation timestamp inRFC3339
    /// text format.
    public var creationTimestamp: Swift.String? = nil

    /// An optional description of this resource. Provide this property when you
    /// create the resource.
    public var description: Swift.String? = nil

    /// The IP family of the gateway IPs for the HA-VPN gateway interfaces. If not
    /// specified, IPV4 will be used.
    public var gatewayIpVersion: VpnGateway.GatewayIpVersion? = nil

    /// Output only. [Output Only] The unique identifier for the resource. This identifier is
    /// defined by the server.
    public var id: Swift.UInt64? = nil

    /// Output only. [Output Only] Type of resource. Always compute#vpnGateway for
    /// VPN gateways.
    public var kind: Swift.String? = nil

    /// A fingerprint for the labels being applied to this VpnGateway, which
    /// is essentially a hash of the labels set used for optimistic locking. The
    /// fingerprint is initially generated by Compute Engine and changes after
    /// every request to modify or update labels. You must always provide an
    /// up-to-date fingerprint hash in order to update or change labels,
    /// otherwise the request will fail with error412 conditionNotMet.
    ///
    /// To see the latest fingerprint, make a get() request to
    /// retrieve a VpnGateway.
    public var labelFingerprint: Foundation.Data? = nil

    /// Labels for this resource. These can only be added or modified by thesetLabels method. Each label key/value pair must comply withRFC1035.
    /// Label values may be empty.
    public var labels: [Swift.String: Swift.String] = [:]

    /// Name of the resource. Provided by the client when the resource is created.
    /// The name must be 1-63 characters long, and comply withRFC1035.
    /// Specifically, the name must be 1-63 characters long and match the regular
    /// expression `[a-z]([-a-z0-9]*[a-z0-9])?` which means the first
    /// character must be a lowercase letter, and all following characters must
    /// be a dash, lowercase letter, or digit, except the last character, which
    /// cannot be a dash.
    public var name: Swift.String? = nil

    /// URL of the network to which this VPN gateway is attached. Provided by the
    /// client when the VPN gateway is created.
    public var network: Swift.String? = nil

    /// Input only. [Input Only] Additional params passed with the request, but not persisted
    /// as part of resource payload.
    public var params: VpnGatewayParams? = nil

    /// Output only. [Output Only] URL of the region where the VPN gateway resides.
    public var region: Swift.String? = nil

    /// Output only. [Output Only] Server-defined URL for the resource.
    public var selfLink: Swift.String? = nil

    /// The stack type for this VPN gateway to identify the IP protocols that are
    /// enabled. Possible values are: IPV4_ONLY,IPV4_IPV6, IPV6_ONLY. If not specified,IPV4_ONLY is used if the gateway IP version isIPV4, or IPV4_IPV6 if the gateway IP version isIPV6.
    public var stackType: VpnGateway.StackType? = nil

    /// The list of VPN interfaces associated with this VPN gateway.
    public var vpnInterfaces: [VpnGatewayVpnGatewayInterface] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `VpnGateway`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VpnGateway().with { $0.creationTimestamp = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let creationTimestamp = CodingKeys(stringValue: "creationTimestamp")
      static let description = CodingKeys(stringValue: "description")
      static let gatewayIpVersion = CodingKeys(stringValue: "gatewayIpVersion")
      static let id = CodingKeys(stringValue: "id")
      static let kind = CodingKeys(stringValue: "kind")
      static let labelFingerprint = CodingKeys(stringValue: "labelFingerprint")
      static let labels = CodingKeys(stringValue: "labels")
      static let name = CodingKeys(stringValue: "name")
      static let network = CodingKeys(stringValue: "network")
      static let params = CodingKeys(stringValue: "params")
      static let region = CodingKeys(stringValue: "region")
      static let selfLink = CodingKeys(stringValue: "selfLink")
      static let stackType = CodingKeys(stringValue: "stackType")
      static let vpnInterfaces = CodingKeys(stringValue: "vpnInterfaces")

      static let _knownKeys: Set<Swift.String> = [
        "creationTimestamp",
        "description",
        "gatewayIpVersion",
        "id",
        "kind",
        "labelFingerprint",
        "labels",
        "name",
        "network",
        "params",
        "region",
        "selfLink",
        "stackType",
        "vpnInterfaces",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.creationTimestamp = try container.decodeIfPresent(
        Swift.String.self, forKey: .creationTimestamp)
      self.description = try container.decodeIfPresent(Swift.String.self, forKey: .description)
      self.gatewayIpVersion = try container.decodeIfPresent(
        VpnGateway.GatewayIpVersion.self, forKey: .gatewayIpVersion)
      self.id = try container.decodeIfPresent(Swift.UInt64.self, forKey: .id)
      self.kind = try container.decodeIfPresent(Swift.String.self, forKey: .kind)
      if let s = try container.decodeIfPresent(Swift.String.self, forKey: .labelFingerprint) {
        guard let v = GoogleCloudWKT._DiscoveryBase64.decode(s) else {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath, debugDescription: "Expected url-safe encoded value")
          )
        }
        self.labelFingerprint = v
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .labels)
      {
        self.labels = value
      }
      self.name = try container.decodeIfPresent(Swift.String.self, forKey: .name)
      self.network = try container.decodeIfPresent(Swift.String.self, forKey: .network)
      self.params = try container.decodeIfPresent(VpnGatewayParams.self, forKey: .params)
      self.region = try container.decodeIfPresent(Swift.String.self, forKey: .region)
      self.selfLink = try container.decodeIfPresent(Swift.String.self, forKey: .selfLink)
      self.stackType = try container.decodeIfPresent(VpnGateway.StackType.self, forKey: .stackType)
      if let value = try container.decodeIfPresent(
        [VpnGatewayVpnGatewayInterface].self, forKey: .vpnInterfaces)
      {
        self.vpnInterfaces = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.creationTimestamp, forKey: .creationTimestamp)
      try container.encodeIfPresent(self.description, forKey: .description)
      try container.encodeIfPresent(self.gatewayIpVersion, forKey: .gatewayIpVersion)
      try container.encodeIfPresent(self.id, forKey: .id)
      try container.encodeIfPresent(self.kind, forKey: .kind)
      if let v = labelFingerprint {
        try container.encode(
          GoogleCloudWKT._DiscoveryBase64.encode(v), forKey: .labelFingerprint
        )
      }
      try container.encode(self.labels, forKey: .labels)
      try container.encodeIfPresent(self.name, forKey: .name)
      try container.encodeIfPresent(self.network, forKey: .network)
      try container.encodeIfPresent(self.params, forKey: .params)
      try container.encodeIfPresent(self.region, forKey: .region)
      try container.encodeIfPresent(self.selfLink, forKey: .selfLink)
      try container.encodeIfPresent(self.stackType, forKey: .stackType)
      try container.encode(self.vpnInterfaces, forKey: .vpnInterfaces)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The enumerated type for the [gatewayIpVersion][google.cloud.compute.v1.VpnGateway.gatewayIpVersion] field.
    ///
    /// [google.cloud.compute.v1.VpnGateway.gatewayIpVersion]: <doc:VpnGateway/GatewayIpVersion>
    public enum GatewayIpVersion: Codable, Equatable, Sendable {
      /// Every HA-VPN gateway interface is configured with an IPv4 address.
      case ipv4
      /// Every HA-VPN gateway interface is configured with an IPv6 address.
      case ipv6
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .ipv4
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .ipv4: return 0
        case .ipv6: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .ipv4: return "IPV4"
        case .ipv6: return "IPV6"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:GatewayIpVersion/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "IPV4": self = .ipv4
        case "IPV6": self = .ipv6
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:GatewayIpVersion/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .ipv4
        case 1: self = .ipv6
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .ipv4: return try container.encode("IPV4")
        case .ipv6: return try container.encode("IPV6")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The enumerated type for the [stackType][google.cloud.compute.v1.VpnGateway.stackType] field.
    ///
    /// [google.cloud.compute.v1.VpnGateway.stackType]: <doc:VpnGateway/StackType>
    public enum StackType: Codable, Equatable, Sendable {
      /// Enable VPN gateway with both IPv4 and IPv6 protocols.
      case ipv4Ipv6
      /// Enable VPN gateway with only IPv4 protocol.
      case ipv4Only
      /// Enable VPN gateway with only IPv6 protocol.
      case ipv6Only
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .ipv4Ipv6
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .ipv4Ipv6: return 0
        case .ipv4Only: return 1
        case .ipv6Only: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .ipv4Ipv6: return "IPV4_IPV6"
        case .ipv4Only: return "IPV4_ONLY"
        case .ipv6Only: return "IPV6_ONLY"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StackType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "IPV4_IPV6": self = .ipv4Ipv6
        case "IPV4_ONLY": self = .ipv4Only
        case "IPV6_ONLY": self = .ipv6Only
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StackType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .ipv4Ipv6
        case 1: self = .ipv4Only
        case 2: self = .ipv6Only
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .ipv4Ipv6: return try container.encode("IPV4_IPV6")
        case .ipv4Only: return try container.encode("IPV4_ONLY")
        case .ipv6Only: return try container.encode("IPV6_ONLY")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.compute.v1.VpnGateway"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
