// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if VpnGateways
  import Foundation
  import GoogleCloudWkt
  import GoogleCloudGax

  extension Clients {
    protocol VpnGatewaysStub: Sendable {
      func aggregatedList(
        request: VpnGatewaysClient.AggregatedListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.VpnGatewayAggregatedList

      func delete(
        request: VpnGatewaysClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func `get`(
        request: VpnGatewaysClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.VpnGateway

      func getStatus(
        request: VpnGatewaysClient.GetStatusRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.VpnGatewaysGetStatusResponse

      func insert(
        request: VpnGatewaysClient.InsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func list(
        request: VpnGatewaysClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.VpnGatewayList

      func setLabels(
        request: VpnGatewaysClient.SetLabelsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation

      func testIamPermissions(
        request: VpnGatewaysClient.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.TestPermissionsResponse

      func getOperation(
        request: RegionOperationsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation
    }
  }
#endif
