// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if WireGroups
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif

  import GoogleCloudAuth
  import GoogleCloudGax
  import GoogleCloudWkt
  import Logging

  /// Service for the `wireGroups` resource.
  ///
  /// @Snippet(path: "wireGroupsQuickstart")
  public protocol WireGroups {
    /// Deletes the specified wire group in the given scope.
    ///
    /// @Snippet(path: "wireGroups_delete")
    func delete(request: Clients.WireGroupsClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Deletes the specified wire group in the given scope.
    func delete(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
      wireGroup: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Gets the specified wire group resource in the given scope.
    ///
    /// @Snippet(path: "wireGroups_get")
    func `get`(request: Clients.WireGroupsClient.GetRequest) async throws
      -> GoogleCloudComputeV1.WireGroup

    /// Gets the specified wire group resource in the given scope.
    func `get`(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
      wireGroup: Swift.String,
    ) async throws -> GoogleCloudComputeV1.WireGroup

    /// Creates a wire group in the specified project in the given scope
    /// using the parameters that are included in the request.
    ///
    /// @Snippet(path: "wireGroups_insert")
    func insert(request: Clients.WireGroupsClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Creates a wire group in the specified project in the given scope
    /// using the parameters that are included in the request.
    func insert(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
      body: WireGroup?,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Lists the wire groups for a project in the given scope.
    ///
    /// @Snippet(path: "wireGroups_list")
    func list(request: Clients.WireGroupsClient.ListRequest) async throws
      -> GoogleCloudComputeV1.WireGroupList

    /// Lists the wire groups for a project in the given scope.
    func list(
      byItem: Clients.WireGroupsClient.ListRequest
    ) throws -> any AsyncSequence<WireGroup, Swift.Error>

    /// Lists the wire groups for a project in the given scope.
    func list(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
    ) throws -> any AsyncSequence<WireGroup, Swift.Error>

    /// Updates the specified wire group resource with the data included in the
    /// request. This method supportsPATCH
    /// semantics and usesJSON merge
    /// patch format and processing rules.
    ///
    /// @Snippet(path: "wireGroups_patch")
    func patch(request: Clients.WireGroupsClient.PatchRequest) async throws
      -> GoogleCloudComputeV1.Operation

    /// Updates the specified wire group resource with the data included in the
    /// request. This method supportsPATCH
    /// semantics and usesJSON merge
    /// patch format and processing rules.
    func patch(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
      wireGroup: Swift.String,
      body: WireGroup?,
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Deletes the specified wire group in the given scope.
    ///
    /// @Snippet(path: "wireGroups_delete")
    func delete(
      request: Clients.WireGroupsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Gets the specified wire group resource in the given scope.
    ///
    /// @Snippet(path: "wireGroups_get")
    func `get`(
      request: Clients.WireGroupsClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.WireGroup

    /// Creates a wire group in the specified project in the given scope
    /// using the parameters that are included in the request.
    ///
    /// @Snippet(path: "wireGroups_insert")
    func insert(
      request: Clients.WireGroupsClient.InsertRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation

    /// Lists the wire groups for a project in the given scope.
    ///
    /// @Snippet(path: "wireGroups_list")
    func list(
      request: Clients.WireGroupsClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.WireGroupList

    /// Lists the wire groups for a project in the given scope.
    func list(
      byItem: Clients.WireGroupsClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<WireGroup, Swift.Error>

    /// Updates the specified wire group resource with the data included in the
    /// request. This method supportsPATCH
    /// semantics and usesJSON merge
    /// patch format and processing rules.
    ///
    /// @Snippet(path: "wireGroups_patch")
    func patch(
      request: Clients.WireGroupsClient.PatchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation
  }

  extension Clients {
    /// The recommended implementation for ``WireGroups``.
    public class WireGroupsClient: WireGroups {
      let inner: any WireGroupsStub

      /// Creates a new `WireGroupsClient` instance.
      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        var inner: any WireGroupsStub = try WireGroupsTransport(options)
        inner = WireGroupsRetry(inner, options: options)
        if let logger = options.logger {
          inner = WireGroupsLogging(inner, logger: logger)
        }
        self.inner = inner
      }

      /// See `WireGroups.delete`
      public func delete(
        request: Clients.WireGroupsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.delete(request: request, options: options)
      }

      /// See `WireGroups.`get``
      public func `get`(
        request: Clients.WireGroupsClient.GetRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.WireGroup {
        try await self.inner.`get`(request: request, options: options)
      }

      /// See `WireGroups.insert`
      public func insert(
        request: Clients.WireGroupsClient.InsertRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.insert(request: request, options: options)
      }

      /// See `WireGroups.list`
      public func list(
        request: Clients.WireGroupsClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.WireGroupList {
        try await self.inner.list(request: request, options: options)
      }

      /// Lists the wire groups for a project in the given scope.
      public func list(
        byItem: Clients.WireGroupsClient.ListRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<WireGroup, Swift.Error> {
        let listRpc = { (token: String) async throws -> GoogleCloudComputeV1.WireGroupList in
          var request = byItem
          request.pageToken = token
          return try await self.list(request: request, options: options)
        }
        return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
      }

      /// See `WireGroups.patch`
      public func patch(
        request: Clients.WireGroupsClient.PatchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudComputeV1.Operation {
        try await self.inner.patch(request: request, options: options)
      }
    }
  }

  // Default implementations
  extension WireGroups {
    public func delete(request: Clients.WireGroupsClient.DeleteRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.delete(request: request, options: .init())
    }

    public func delete(
      request: Clients.WireGroupsClient.DeleteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func delete(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
      wireGroup: Swift.String,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.WireGroupsClient.DeleteRequest().with {
        $0.project = project
        $0.crossSiteNetwork = crossSiteNetwork
        $0.wireGroup = wireGroup
      }
      return try await self.delete(request: request)
    }

    public func `get`(request: Clients.WireGroupsClient.GetRequest) async throws
      -> GoogleCloudComputeV1.WireGroup
    {
      try await self.`get`(request: request, options: .init())
    }

    public func `get`(
      request: Clients.WireGroupsClient.GetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.WireGroup {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func `get`(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
      wireGroup: Swift.String,
    ) async throws -> GoogleCloudComputeV1.WireGroup {
      let request = Clients.WireGroupsClient.GetRequest().with {
        $0.project = project
        $0.crossSiteNetwork = crossSiteNetwork
        $0.wireGroup = wireGroup
      }
      return try await self.`get`(request: request)
    }

    public func insert(request: Clients.WireGroupsClient.InsertRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.insert(request: request, options: .init())
    }

    public func insert(
      request: Clients.WireGroupsClient.InsertRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func insert(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
      body: WireGroup?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.WireGroupsClient.InsertRequest().with {
        $0.project = project
        $0.crossSiteNetwork = crossSiteNetwork
        $0.body = body
      }
      return try await self.insert(request: request)
    }

    public func list(request: Clients.WireGroupsClient.ListRequest) async throws
      -> GoogleCloudComputeV1.WireGroupList
    {
      try await self.list(request: request, options: .init())
    }

    public func list(
      request: Clients.WireGroupsClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.WireGroupList {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func list(
      byItem: Clients.WireGroupsClient.ListRequest
    ) throws -> any AsyncSequence<WireGroup, Swift.Error> {
      try self.list(byItem: byItem, options: .init())
    }

    public func list(
      byItem: Clients.WireGroupsClient.ListRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<WireGroup, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudComputeV1.WireGroupList in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func list(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
    ) throws -> any AsyncSequence<WireGroup, Swift.Error> {
      let request = Clients.WireGroupsClient.ListRequest().with {
        $0.project = project
        $0.crossSiteNetwork = crossSiteNetwork
      }
      return try self.list(byItem: request)
    }

    public func patch(request: Clients.WireGroupsClient.PatchRequest) async throws
      -> GoogleCloudComputeV1.Operation
    {
      try await self.patch(request: request, options: .init())
    }

    public func patch(
      request: Clients.WireGroupsClient.PatchRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudComputeV1.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func patch(
      project: Swift.String,
      crossSiteNetwork: Swift.String,
      wireGroup: Swift.String,
      body: WireGroup?,
    ) async throws -> GoogleCloudComputeV1.Operation {
      let request = Clients.WireGroupsClient.PatchRequest().with {
        $0.project = project
        $0.crossSiteNetwork = crossSiteNetwork
        $0.wireGroup = wireGroup
        $0.body = body
      }
      return try await self.patch(request: request)
    }
  }
#endif
